import { describe, expect, it, vi } from 'vitest';
vi.mock('../prisma/prisma.service.js',()=>({PrismaService:class{}}));
vi.mock('../auth/auth.service.js',()=>({AuthService:class{}}));
vi.mock('../realtime/realtime.gateway.js',()=>({RealtimeGateway:class{}}));
vi.mock('../generated/prisma/client.js',()=>({UserRole:{CUSTOMER:'CUSTOMER'}}));
import { AddressesService } from './addresses.service.js';
const data:any={street:'Rua A',number:'10',neighborhood:'Centro',city:'Porto Seguro',state:'BA',postalCode:'45810-000'};
function fixture(){const found:any={id:'a',userId:'u',...data,postalCode:'45810000',latitude:-16.45,longitude:-39.064,locationConfirmed:true,isDefault:false};const address:any={findFirst:vi.fn(async()=>found),update:vi.fn(async({data}:any)=>({...found,...data})),updateMany:vi.fn(),count:vi.fn(async()=>0),create:vi.fn(async({data}:any)=>({id:'a',...data}))};const db:any={address,$transaction:async(fn:any)=>fn({address})};const pricing:any={selectedLocation:vi.fn(async()=>({latitude:-16.46,longitude:-39.07,locationConfirmed:true}))};const events:any={emitToUser:vi.fn(),emitToRole:vi.fn()};return{address,events,pricing,service:new AddressesService(db,{authenticate:async()=>({id:'u',role:'CUSTOMER'})}as any,events,pricing)}}
describe('Localização e gestão dos endereços',()=>{
 it('persiste referência e coordenadas validadas do estabelecimento, ignorando coordenadas do cliente',async()=>{const f=fixture();const r=await f.service.create({...data,locationRef:'hotel-ref',latitude:0,longitude:0});expect(f.pricing.selectedLocation).toHaveBeenCalled();expect(r).toMatchObject({locationRef:'hotel-ref',latitude:-16.46,longitude:-39.07,locationConfirmed:true});expect(f.events.emitToUser).toHaveBeenCalled()});
 it('não salva nem publica evento quando a seleção é inválida',async()=>{const f=fixture();f.pricing.selectedLocation.mockRejectedValue(new Error('Selecione novamente'));await expect(f.service.create({...data,locationRef:'invalid'})).rejects.toThrow('Selecione');expect(f.address.create).not.toHaveBeenCalled();expect(f.events.emitToUser).not.toHaveBeenCalled()});

 it('limpa coordenadas ao alterar a rua sem confirmar um novo ponto',async()=>{const f=fixture();const r=await f.service.update('a',{...data,street:'Rua B'});expect(r).toMatchObject({latitude:null,longitude:null,locationConfirmed:false});expect(f.events.emitToUser).toHaveBeenCalledWith('u','addresses.updated',expect.any(Object))});
 it('mantém o ponto ao trocar somente o nome e o endereço principal',async()=>{const f=fixture();const r=await f.service.update('a',{...data,label:'Casa',isDefault:true});expect(r.locationConfirmed).toBe(true);expect(r.latitude).toBe(-16.45);expect(r.postalCode).toBe('45810000')});
 it('persiste um novo ponto confirmado',async()=>{const f=fixture();const r=await f.service.update('a',{...data,latitude:-16.46,longitude:-39.07});expect(r).toMatchObject({latitude:-16.46,longitude:-39.07,locationConfirmed:true})});
 it('recusa coordenadas incompletas e fora do alcance',async()=>{const f=fixture();await expect(f.service.create({...data,latitude:-16.45})).rejects.toThrow('mapa');await expect(f.service.create({...data,latitude:91,longitude:0})).rejects.toThrow('mapa');expect(f.address.create).not.toHaveBeenCalled()});
 it('não altera endereço de outra conta',async()=>{const f=fixture();f.address.findFirst.mockResolvedValue(null);await expect(f.service.update('other',data)).rejects.toThrow('não encontrado');expect(f.address.findFirst).toHaveBeenCalledWith({where:{id:'other',userId:'u'}});expect(f.address.update).not.toHaveBeenCalled()});
 it('marca o primeiro endereço como principal e publica somente após salvar',async()=>{const f=fixture();const r=await f.service.create({...data,isDefault:false,latitude:-16.45,longitude:-39.064});expect(r.isDefault).toBe(true);expect(r.locationConfirmed).toBe(true);f.address.create.mockRejectedValue(new Error('db'));f.events.emitToUser.mockClear();await expect(f.service.create(data)).rejects.toThrow('db');expect(f.events.emitToUser).not.toHaveBeenCalled()});
});
