ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fulfillmentHold" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "refundedTotal" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "creditedTotal" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "storeCreditUsed" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "availabilityStatus" TEXT NOT NULL DEFAULT 'AVAILABLE';
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "availabilityNote" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "availabilityOptions" JSONB;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "issueId" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "originalProductName" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "customerChoice" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "stripeRefundId" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "refundStatus" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "refundAttempt" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "refundAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "creditAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "storeCreditShare" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "resolvedAt" TIMESTAMP(3);
CREATE TABLE IF NOT EXISTS "CustomerCreditEntry" (
 "id" TEXT NOT NULL PRIMARY KEY,"customerId" TEXT NOT NULL,"amount" DECIMAL(10,2) NOT NULL,
 "idempotencyKey" TEXT NOT NULL,"description" TEXT NOT NULL,"orderId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "CustomerCreditEntry_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "CustomerCreditEntry_idempotencyKey_key" ON "CustomerCreditEntry"("idempotencyKey");
CREATE INDEX IF NOT EXISTS "CustomerCreditEntry_customerId_createdAt_idx" ON "CustomerCreditEntry"("customerId","createdAt");
