'use client';

import { useEffect, useRef, useState } from 'react';
import { Archive, Check, ChevronDown, ImageIcon, Package, Pencil, Plus, Search, Store, X } from 'lucide-react';

type Row = Record<string, any>;
const money = (value: any) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const emptyProduct = (categoryId = '') => ({ categoryId, name: '', description: '', imageUrl: '', price: '', stock: 0, active: true });

export default function CatalogPanel({ categories, pricing, act }: { categories: Row[], pricing: Row, act: (path: string, method: string, body: Row) => Promise<any> }) {
  const [query, setQuery] = useState(''), [category, setCategory] = useState('all'), [filter, setFilter] = useState('all');
  const [limit, setLimit] = useState(24), [editor, setEditor] = useState<'product' | 'category' | 'store' | null>(null);
  const [form, setForm] = useState<Row>({}), [saving, setSaving] = useState(false), [notice, setNotice] = useState('');
  const [confirm, setConfirm] = useState<{ path: string, name: string, archived: boolean } | null>(null);
  const previousFocus = useRef<HTMLElement | null>(null), modal = useRef<HTMLElement | null>(null);
  const all = categories.flatMap(c => (c.products || []).map((p: Row) => ({ ...p, category: c })));
  const visible = all.filter(p => (category === 'all' || p.categoryId === category) && `${p.name} ${p.description || ''} ${p.category.name}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')) && (filter === 'archived' ? p.archived || p.category.archived : !p.archived && !p.category.archived && (filter === 'all' || (filter === 'available' ? p.active && p.stock > 0 && p.category.active : filter === 'stock' ? p.stock <= 0 : !p.active || !p.category.active))));
  const live = all.filter(p => !p.archived && !p.category.archived);
  useEffect(() => { setLimit(24); }, [query, category, filter]);
  useEffect(() => {
    if (!editor && !confirm) return;
    previousFocus.current = document.activeElement as HTMLElement;
    const before = document.body.style.overflow; document.body.style.overflow = 'hidden';
    const id = requestAnimationFrame(() => modal.current?.querySelector<HTMLElement>('input, button')?.focus());
    const key = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && !saving) { setEditor(null); setConfirm(null); }
      if (e.key === 'Tab') {
        const nodes = Array.from(modal.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)') || []);
        const first = nodes[0], last = nodes[nodes.length - 1];
        if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); }
        else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); }
      }
    };
    document.addEventListener('keydown', key);
    return () => { cancelAnimationFrame(id); document.body.style.overflow = before; document.removeEventListener('keydown', key); previousFocus.current?.focus(); };
  }, [editor, confirm, saving]);
  const change = (key: string, value: any) => setForm(f => ({ ...f, [key]: value }));
  const open = (kind: 'product' | 'category' | 'store', data: Row) => { setForm({ ...data }); setNotice(''); setEditor(kind); };
  const mutate = async (path: string, body: Row, success: string, method = 'PATCH') => {
    if (saving) return null; setSaving(true); setNotice('');
    try { const result = await act(path, method, body); if (result) setNotice(success); return result; }
    finally { setSaving(false); }
  };
  const save = async (e: React.FormEvent) => {
    e.preventDefault(); const id = form.id;
    const path = editor === 'store' ? '/admin/store' : `/admin/${editor === 'product' ? 'products' : 'categories'}${id ? '/' + id : ''}`;
    const body = editor === 'product' ? { name: form.name, categoryId: form.categoryId, description: form.description || '', imageUrl: form.imageUrl || '', price: Number(form.price), stock: Number(form.stock), active: form.active } : editor === 'category' ? { name: form.name, imageUrl: form.imageUrl || '', position: Number(form.position || 0), active: form.active } : { storeOpen: form.storeOpen, storeMessage: form.storeMessage };
    if (await mutate(path, body, 'Alteração salva e enviada ao app.', id || editor === 'store' ? 'PATCH' : 'POST')) setEditor(null);
  };
  const close = () => { if (!saving) { setEditor(null); setConfirm(null); } };
  const field = (key: string, label: string, type = 'text', props: Row = {}) => <label>{label}<input type={type} value={form[key] ?? ''} onChange={e => change(key, e.target.value)} {...props}/></label>;
  const archive = (path: string, item: Row) => setConfirm({ path, name: item.name, archived: !item.archived });
  return <div className="primeCatalog">
    <section className={`catalogStoreHero ${pricing.storeOpen === false ? 'closed' : ''}`}>
      <div className="catalogStoreMark"><Store size={30}/></div><div className="catalogStoreCopy"><small>VITRINE PORTO PRIME</small><h2>{pricing.storeOpen === false ? 'Uma pausa, com tudo sob controle.' : 'Sua loja pronta para vender.'}</h2><p>{pricing.storeOpen === false ? pricing.storeMessage : 'Organize a vitrine, controle o estoque e publique no app.'}</p><span className="catalogStatus"><i/>{pricing.storeOpen === false ? 'Loja fechada · novos pedidos pausados' : 'Loja aberta · recebendo pedidos'}</span></div>
      <button disabled={saving} className="catalogStoreAction" onClick={() => open('store', { storeOpen: pricing.storeOpen === false, storeMessage: pricing.storeMessage || 'Voltaremos em breve. Sua sacola continua salva.' })}>{pricing.storeOpen === false ? 'Abrir loja' : 'Fechar loja'}</button>
    </section>
    <div className="catalogStats">{[[Package, 'Produtos na vitrine', live.length], [Check, 'Disponíveis', live.filter(p => p.active && p.stock > 0 && p.category.active).length], [Archive, 'Sem estoque', live.filter(p => p.stock <= 0).length], [Store, 'Categorias', categories.filter(c => !c.archived).length]].map(([Icon, label, value]: any) => <div key={label}><Icon size={19}/><span>{label}<b>{value}</b></span></div>)}</div>
    <div className="catalogSectionHead"><div><small>CURADORIA E ESTOQUE</small><h3>Seu catálogo, bem organizado</h3></div><div className="catalogActions"><button className="secondary" onClick={() => open('category', { name: '', imageUrl: '', position: categories.length, active: true })}><Plus size={16}/>Categoria</button><button onClick={() => open('product', emptyProduct(categories.find(c => !c.archived)?.id))}><Plus size={16}/>Novo produto</button></div></div>
    {notice && <p className="catalogNotice" role="status"><Check size={16}/>{notice}</p>}
    <div className="catalogFilters"><label className="catalogSearch"><Search size={18}/><input aria-label="Buscar produtos" placeholder="Nome, descrição ou categoria" value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label="Filtrar categoria" value={category} onChange={e => setCategory(e.target.value)}><option value="all">Todas as categorias</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}{c.archived ? ' (arquivada)' : ''}</option>)}</select><select aria-label="Filtrar disponibilidade" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Todos os produtos</option><option value="available">Disponíveis</option><option value="unavailable">Indisponíveis</option><option value="stock">Sem estoque</option><option value="archived">Arquivados</option></select></div>
    <div className="catalogWorkspace"><aside className="catalogCategoryList"><div className="catalogSectionHead"><h3>Categorias</h3><small>{categories.length}</small></div>{categories.map(c => <div className={`catalogCategoryRow ${c.archived ? 'muted' : ''}`} key={c.id}><button className={`catalogCategorySelect ${category === c.id ? 'selected' : ''}`} onClick={() => setCategory(category === c.id ? 'all' : c.id)}><span>{c.name}<small>{(c.products || []).filter((p: Row) => !p.archived).length} produtos · {c.archived ? 'arquivada' : c.active ? 'ativa' : 'pausada'}</small></span><ChevronDown size={14}/></button><div className="catalogCategoryTools"><button aria-label={`Editar ${c.name}`} onClick={() => open('category', c)}><Pencil size={15}/></button><button disabled={saving} onClick={() => mutate('/admin/categories/' + c.id, { active: !c.active }, 'Categoria atualizada.')}>{c.active ? 'Pausar' : 'Ativar'}</button><button disabled={saving} aria-label={`${c.archived ? 'Restaurar' : 'Arquivar'} ${c.name}`} onClick={() => archive('/admin/categories/' + c.id, c)}><Archive size={15}/></button></div></div>)}</aside>
    <section className="catalogProductsArea"><div className="catalogResultCount">{visible.length} produto{visible.length === 1 ? '' : 's'} encontrado{visible.length === 1 ? '' : 's'}<span>Alterações publicadas após salvar</span></div><div className="catalogPremiumGrid">{visible.slice(0, limit).map(p => <article key={p.id} className="catalogProductCard"><div className="catalogProductImage">{p.imageUrl ? <img loading="lazy" src={p.imageUrl} alt={p.name} onError={e => { e.currentTarget.style.display = 'none'; }}/>: <ImageIcon size={34}/>}<span className={`catalogProductBadge ${p.archived || p.category.archived || !p.active || !p.category.active || p.stock <= 0 ? 'paused' : ''}`}>{p.archived || p.category.archived ? 'Arquivado' : !p.active || !p.category.active ? 'Indisponível' : p.stock <= 0 ? 'Sem estoque' : 'Disponível'}</span></div><div className="catalogProductBody"><small>{p.category.name}</small><h4>{p.name}</h4><p>{p.description || 'Sem descrição cadastrada'}</p><div className="catalogProductValue"><b>{money(p.price)}</b><span>{p.stock} un. em estoque</span></div></div><footer><button className="secondary" onClick={() => open('product', p)}><Pencil size={15}/>Editar</button><button disabled={saving} className="secondary" onClick={() => mutate('/admin/products/' + p.id, { active: !p.active }, 'Disponibilidade atualizada.')}>{p.active ? 'Indisponível' : 'Disponibilizar'}</button><button disabled={saving} className="catalogArchive" aria-label={`${p.archived ? 'Restaurar' : 'Arquivar'} ${p.name}`} onClick={() => archive('/admin/products/' + p.id, p)}><Archive size={16}/></button></footer></article>)}</div>{!visible.length && <div className="catalogEmpty"><Package size={36}/><h3>Nenhum produto por aqui</h3><p>Experimente outro filtro ou prepare um novo produto para sua vitrine.</p><button onClick={() => open('product', emptyProduct(categories.find(c => !c.archived)?.id))}>Adicionar produto</button></div>}{visible.length > limit && <button className="catalogMore secondary" onClick={() => setLimit(n => n + 24)}>Mostrar mais produtos</button>}</section></div>
    {(editor || confirm) && <div className="catalogModalBackdrop" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><section ref={modal} className="catalogEditor" role="dialog" aria-modal="true" aria-labelledby="catalog-editor-title"><header><div><small>{confirm ? 'ORGANIZAR CATÁLOGO' : 'PUBLICAÇÃO NO APP'}</small><h2 id="catalog-editor-title">{confirm ? `${confirm.archived ? 'Arquivar' : 'Restaurar'} registro` : editor === 'store' ? form.storeOpen ? 'Abrir a loja' : 'Pausar novos pedidos' : `${form.id ? 'Editar' : 'Criar'} ${editor === 'product' ? 'produto' : 'categoria'}`}</h2></div><button type="button" className="secondary" aria-label="Fechar" disabled={saving} onClick={close}><X size={19}/></button></header>
    {confirm ? <><p><strong>{confirm.name}</strong></p><p>{confirm.archived ? 'O registro sai da vitrine. Produtos, pedidos e histórico ficam preservados; você pode restaurá-lo depois.' : 'O registro volta ao catálogo com sua disponibilidade e estoque anteriores. Categorias pausadas continuam ocultas no app.'}</p><div className="catalogEditorActions"><button className="secondary" disabled={saving} onClick={close}>Cancelar</button><button disabled={saving} onClick={async () => { if (await mutate(confirm.path, { archived: confirm.archived }, 'Catálogo atualizado.')) setConfirm(null); }}>{saving ? 'Salvando…' : confirm.archived ? 'Arquivar' : 'Restaurar'}</button></div></> : <form onSubmit={save}><div className="catalogEditorFields">
    {editor === 'store' ? <><p className="catalogFormNote">{form.storeOpen ? 'Clientes poderão finalizar novos pedidos novamente.' : 'A vitrine continua acessível. Novos pedidos ficam bloqueados; pagamentos e entregas já iniciados continuam normalmente.'}</p><label className="full">Mensagem exibida quando a loja estiver fechada<textarea maxLength={240} required value={form.storeMessage || ''} onChange={e => change('storeMessage', e.target.value)}/></label></> : <>{field('name', editor === 'product' ? 'Nome do produto' : 'Nome da categoria', 'text', { required: true, maxLength: editor === 'product' ? 160 : 100 })}{editor === 'product' ? <><label>Categoria<select required value={form.categoryId || ''} onChange={e => change('categoryId', e.target.value)}><option value="">Selecione</option>{categories.filter(c => !c.archived || c.id === form.categoryId).map(c => <option key={c.id} value={c.id} disabled={c.archived}>{c.name}</option>)}</select></label>{field('price', 'Preço (R$)', 'number', { min: 0, max: 99999999.99, step: '.01', required: true })}{field('stock', 'Quantidade em estoque', 'number', { min: 0, max: 2147483647, step: 1, required: true })}<label className="full">Descrição<textarea maxLength={2000} value={form.description || ''} onChange={e => change('description', e.target.value)}/></label></> : field('position', 'Ordem de exibição', 'number', { min: 0, step: 1, required: true })}<label className="full">Imagem do seu catálogo · URL HTTPS<input type="url" pattern="https://.*" maxLength={2048} value={form.imageUrl || ''} onChange={e => change('imageUrl', e.target.value)} placeholder="https://…"/><small>Use uma imagem própria já hospedada. Deixe vazio para remover.</small></label>{form.imageUrl && <div className="catalogImagePreview full"><img src={form.imageUrl} alt="Prévia da imagem"/></div>}<label className="catalogCheckbox full"><input type="checkbox" checked={form.active === true} onChange={e => change('active', e.target.checked)}/><span>{editor === 'product' ? 'Disponível para venda quando houver estoque e categoria ativa' : 'Categoria visível no app'}</span></label></>}
    </div><div className="catalogEditorActions"><button type="button" className="secondary" onClick={close} disabled={saving}>Cancelar</button><button disabled={saving}>{saving ? 'Salvando…' : editor === 'store' ? form.storeOpen ? 'Confirmar abertura' : 'Confirmar fechamento' : 'Salvar alterações'}</button></div></form>}
    </section></div>}
  </div>;
}
