"use client";
import { useEffect, useState } from "react";
import { Bike, Check, MapPin, Save } from "lucide-react";
import OriginMap from "./origin-map";
import { displayMessage } from "./ui-messages";
type Row = Record<string, any>;
const money = (n:number) => n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function DeliverySettings({pricing,act}:{pricing:Row,act:any}) {
 const [form,setForm]=useState<Row>(pricing||{}), [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(false);
 useEffect(()=>{if(!dirty&&!busy)setForm(pricing||{})},[pricing,dirty,busy]);
 const change=(k:string,v:any)=>{setForm(f=>({...f,[k]:v}));setDirty(true);setSuccess(false)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError("");try{const result=await act("/delivery/pricing-config","PATCH",{baseFee:Number(form.baseFee),includedKm:Number(form.includedKm),pricePerAdditionalKm:Number(form.pricePerAdditionalKm),distributorName:form.distributorName,distributorAddress:form.distributorAddress,...(form.distributorLatitude!=null&&form.distributorLongitude!=null?{distributorLatitude:Number(form.distributorLatitude),distributorLongitude:Number(form.distributorLongitude)}:{})});if(!result)throw new Error("Não foi possível salvar os valores. Tente novamente.");setDirty(false);setSuccess(true)}catch(e){setError(displayMessage(e))}finally{setBusy(false)}};
 const estimate=(km:number)=>Number(form.baseFee||0)+Math.max(0,km-Number(form.includedKm||0))*Number(form.pricePerAdditionalKm||0);
 const field=(k:string,label:string,hint:string,min:number)=><label className="deliveryPriceField"><span>{label}</span><input required type="number" min={min} max="1000" step="0.01" value={form[k]??""} onChange={e=>change(k,e.target.value)}/><small>{hint}</small></label>;
 return <form className="deliverySettings" onSubmit={save}><section className="deliveryHero"><div><span className="deliveryEyebrow">ENTREGA PORTO PRIME</span><h2>Uma regra simples.<br/>Uma entrega justa.</h2><p>Configure os valores. O cliente vê a taxa calculada pela rota até o endereço confirmado.</p></div><div className="deliveryShare"><Bike size={30}/><b>100%</b><span>da taxa para o motoboy</span></div></section><section className="panel"><div className="panelHead"><div><h3>Seu preço de entrega</h3><span>As alterações valem para os próximos orçamentos. Pedidos já criados mantêm seus valores.</span></div></div><div className="deliveryPrices">{field("baseFee","Taxa inicial · R$","Valor para o trecho incluído",.01)}{field("includedKm","Distância incluída · km","Até essa distância, a taxa é fixa",0)}{field("pricePerAdditionalKm","Adicional por km · R$","Cobrança proporcional ao trecho excedente",.01)}</div><div className="deliveryExamples"><div><small>COMO FICA PARA O CLIENTE</small><p>Taxa inicial + distância excedente × adicional por km</p></div>{[3,5,8].map(km=><div key={km}><span>{km} km de rota</span><b>{money(estimate(km))}</b></div>)}</div></section><section className="panel deliveryOrigin"><div className="panelHead"><div><h3><MapPin size={19}/> Ponto de retirada</h3><span>O início de todas as entregas. Você pode ajustar quando precisar.</span></div><span className="deliveryOriginStatus">{form.distributorLatitude!=null&&form.distributorLongitude!=null?(Number(form.distributorLatitude).toFixed(7)===Number(pricing.distributorLatitude).toFixed(7)&&Number(form.distributorLongitude).toFixed(7)===Number(pricing.distributorLongitude).toFixed(7)?"Ponto salvo":"Novo ponto · salve abaixo"):"Ponto não configurado"}</span></div><div className="originSimpleIntro"><b>Defina a localização exata da loja</b><p>Se estiver na loja, use sua posição. Caso contrário, informe as coordenadas da entrada ou selecione o ponto no mapa. Depois clique em Salvar configuração.</p></div><OriginMap lat={form.distributorLatitude!=null?Number(form.distributorLatitude):null} lng={form.distributorLongitude!=null?Number(form.distributorLongitude):null} onChange={(lat,lng)=>{setForm(f=>({...f,distributorLatitude:lat,distributorLongitude:lng}));setDirty(true);setSuccess(false)}}/></section>{error&&<p role="alert" className="deliveryError">{error}</p>}<div className="deliverySave"><span>{success?<><Check size={18}/> Valores salvos e sincronizados</>:"O despacho automático continua funcionando com suas regras atuais."}</span><button disabled={busy||!dirty} type="submit"><Save size={17}/>{busy?"Salvando…":"Salvar configuração"}</button></div></form>;
}
