"use client";
import {useEffect,useRef,useState} from 'react';
import {Zap,ChevronDown,Check} from 'lucide-react';
import {displayMessage} from './ui-messages';
type Mode='AUTO'|'MANUAL_ON'|'MANUAL_OFF';
type Signal={enabled:boolean;mode:Mode;reason:string|null;bonusAmount:number;waitingCount:number;threshold:number;revision:number;updatedAt:string|null};
export default function DemandControl({request,epoch}:{request:(path:string,method?:string,body?:unknown)=>Promise<Signal>;epoch:number}){
 const [signal,setSignal]=useState<Signal|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[amount,setAmount]=useState('2,50');
 const latest=useRef(-1),writing=useRef(false),dirty=useRef(false);
 function apply(data:Signal){if(typeof data.enabled!=='boolean'||!Number.isInteger(data.revision)||data.revision<latest.current)return;latest.current=data.revision;setSignal(data);if(!dirty.current)setAmount(Number(data.bonusAmount).toFixed(2).replace('.',','));}
 useEffect(()=>{let active=true;if(!writing.current)request('/admin/operations/demand').then(data=>{if(active){apply(data);setError('')}}).catch(e=>{if(active)setError(displayMessage(e))});return()=>{active=false};
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[epoch]);
 async function save(body:unknown){if(!signal||writing.current)return;writing.current=true;setBusy(true);setError('');try{const data=await request('/admin/operations/demand','PATCH',body);dirty.current=false;apply(data)}catch(e){setError(displayMessage(e))}finally{writing.current=false;setBusy(false)}}
 const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <details className={'demandConsole '+(signal?.enabled?'isActive':'')}><summary><span className="demandMark"><Zap size={18}/></span><span><b>Alta demanda {signal?.enabled?'ON':'OFF'}</b><small>{!signal?'Consultando…':signal.enabled?`+${money(signal.bonusAmount)} por entrega · ${signal.reason==='AUTOMATIC'?'Automática':'Manual'}`:signal.mode==='AUTO'?'Monitoramento automático':'Desativada manualmente'}</small></span><ChevronDown size={16}/></summary><div className="demandPanel"><div className="demandPanelHeading"><span>INCENTIVO À EQUIPE</span><strong>Mais agilidade, mais ganhos.</strong><p>Bônus pago pela distribuidora. O valor do cliente permanece igual.</p></div><div className="demandModes" aria-label="Modo de alta demanda">{([['MANUAL_ON','ON'],['MANUAL_OFF','OFF'],['AUTO','Automático']] as [Mode,string][]).map(([mode,label])=><button key={mode} type="button" aria-pressed={signal?.mode===mode} disabled={busy||!signal} onClick={()=>save({mode})}>{signal?.mode===mode&&<Check size={14}/>} {label}</button>)}</div><div className="demandQueue"><b>{signal?.waitingCount??'—'} <small>pedidos em espera</small></b><p>No automático: ativa com 10 pedidos pagos sem motoboy e desativa abaixo de 10. ON e OFF mantêm a escolha manual.</p></div><form onSubmit={e=>{e.preventDefault();void save({bonusAmount:amount.replace(',','.')})}}><label htmlFor="demand-bonus">Adicional por entrega</label><div className="demandAmount"><span>R$</span><input id="demand-bonus" inputMode="decimal" value={amount} disabled={busy||!signal} onChange={e=>{dirty.current=true;setAmount(e.target.value)}}/><button type="submit" disabled={busy||!signal}>{busy?'Salvando…':'Salvar valor'}</button></div><div className="demandPresets">{[2,2.5,3,5].map(n=><button key={n} type="button" disabled={busy||!signal} onClick={()=>{dirty.current=true;setAmount(n.toFixed(2).replace('.',','))}}>{money(n)}</button>)}</div></form><small className="demandGuarantee">O bônus da oferta aceita fica garantido até a conclusão da entrega.</small>{error&&<p className="demandControlError" role="alert">{error}</p>}</div></details>;
}
