"use client";
import {useEffect,useRef,useState} from 'react';
import {Zap,Check,Power,SlidersHorizontal,ShieldCheck,Users} from 'lucide-react';
import {displayMessage} from './ui-messages';
type Mode='AUTO'|'MANUAL_ON'|'MANUAL_OFF';
type Signal={enabled:boolean;mode:Mode;reason:string|null;bonusAmount:number;waitingCount:number;threshold:number;revision:number;updatedAt:string|null};
export default function DemandControl({request,epoch}:{request:(path:string,method?:string,body?:unknown)=>Promise<Signal>;epoch:number}){
 const [signal,setSignal]=useState<Signal|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[amount,setAmount]=useState('2,50');
 const latest=useRef(-1),writing=useRef(false),dirty=useRef(false);
 function apply(data:Signal){if(typeof data.enabled!=='boolean'||!Number.isInteger(data.revision)||data.revision<latest.current)return;latest.current=data.revision;setSignal(data);if(!dirty.current)setAmount(Number(data.bonusAmount).toFixed(2).replace('.',','));}
 useEffect(()=>{let active=true;if(!writing.current)request('/admin/operations/demand').then(data=>{if(active){apply(data);setError('')}}).catch(e=>{if(active)setError(displayMessage(e))});return()=>{active=false};
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[epoch]);
 async function save(body:unknown){if(!signal||writing.current)return;writing.current=true;setBusy(true);setError('');try{const data=await request('/admin/operations/demand','PATCH',body);dirty.current=false;apply(data)}catch(e){setError(displayMessage(e))}finally{writing.current=false;setBusy(false)}}
 const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const modes:[Mode,string,string][]=[['MANUAL_ON','Ativar agora','Mantém o incentivo ligado.'],['MANUAL_OFF','Desativar','Mantém o incentivo desligado.'],['AUTO','Automático','Ativa com 10 pedidos em espera.']];
 return <section className="ppDemand" aria-labelledby="pp-demand-title" aria-busy={busy}>
  <header className="ppDemandHero"><div className="ppDemandIdentity"><span className="ppDemandIcon"><Zap size={24}/></span><div><span className="ppDemandEyebrow">OPERAÇÃO · INCENTIVOS</span><h2 id="pp-demand-title">Alta demanda</h2><p>Um incentivo extra para mobilizar sua equipe.</p></div></div><span className={'ppDemandStatus '+(signal?.enabled?'active':'')} role="status"><span/>{!signal?'Consultando':signal.enabled?'Ativa':'Desativada'}</span></header>
  <div className="ppDemandBody"><div className="ppDemandOperation"><div className="ppDemandSectionHeading"><Power size={18}/><div><h3>Como deseja operar?</h3><p>Escolha o controle manual ou deixe o sistema acompanhar a fila.</p></div></div><div className="ppDemandModeGrid" aria-label="Modo de alta demanda">{modes.map(([mode,label,description])=><button key={mode} type="button" aria-pressed={signal?.mode===mode} disabled={busy||!signal} onClick={()=>save({mode})}><span className="ppDemandModeTop"><span className="ppDemandRadio">{signal?.mode===mode&&<Check size={12}/>}</span><b>{label}</b></span><small>{description}</small></button>)}</div><div className="ppDemandSummary"><div><Users size={18}/><span>Fila de espera<strong>{signal?.waitingCount??'—'} <small>pedidos pagos</small></strong></span></div><div><SlidersHorizontal size={18}/><span>Controle vigente<strong>{!signal?'—':signal.mode==='AUTO'?'Automático':signal.enabled?'Manual · ON':'Manual · OFF'}</strong></span></div></div><p className="ppDemandRule">No automático, ativa a partir de 10 pedidos pagos sem motoboy e desativa abaixo de 10. A escolha manual permanece até você mudar o modo.</p></div>
  <div className="ppDemandBonus"><span className="ppDemandEyebrow">REMUNERAÇÃO ADICIONAL</span><div className="ppDemandCurrent"><strong>{signal?money(signal.bonusAmount):'—'}</strong><span>por entrega elegível</span></div><form onSubmit={e=>{e.preventDefault();void save({bonusAmount:amount.replace(',','.')})}}><label htmlFor="demand-bonus">Definir bônus por entrega</label><div className="ppDemandInput"><span aria-hidden="true">R$</span><input id="demand-bonus" inputMode="decimal" value={amount} disabled={busy||!signal} onChange={e=>{dirty.current=true;setAmount(e.target.value)}} aria-describedby="pp-demand-funding"/></div><div className="ppDemandPresets" aria-label="Sugestões de bônus">{[2,2.5,3,5].map(n=><button key={n} type="button" disabled={busy||!signal} aria-pressed={Number(amount.replace(',','.'))===n} onClick={()=>{dirty.current=true;setAmount(n.toFixed(2).replace('.',','))}}>{money(n)}</button>)}</div><button className="ppDemandSave" type="submit" disabled={busy||!signal}><Check size={16}/>{busy?'Salvando…':'Salvar valor do bônus'}</button></form><p id="pp-demand-funding">Pago pela distribuidora. O total do cliente permanece igual.</p></div></div>
  <footer className="ppDemandFooter"><ShieldCheck size={18}/><span>O bônus da oferta aceita fica garantido até a conclusão da entrega.</span></footer>{error&&<p className="ppDemandError" role="alert">{error}</p>}
 </section>;
}
