'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,Check,ChevronRight,History,Plus,Search,ShieldCheck,Wallet,X} from 'lucide-react';
import {displayMessage} from './ui-messages';
type Row=Record<string,any>;
const brl=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const when=(v:any)=>v?new Date(v).toLocaleString('pt-BR'):'—';
const labels:Row={PENDING:'Solicitado',PROCESSING:'Em processamento',PAID:'Pago',REJECTED:'Rejeitado',CANCELED:'Cancelado',BONUS_CREDIT:'Bônus',ADJUSTMENT_CREDIT:'Crédito administrativo',WITHDRAWAL_DEBIT:'Reserva de saque',DELIVERY_CREDIT:'Entrega',REVERSAL:'Estorno',WITHDRAWAL_REQUESTED:'Solicitação de saque'};
const Status=({value}:{value:string})=><span className={`financeStatus ${value.toLowerCase()}`}>{labels[value]||value}</span>;
export default function FinancePanel({token,rows,api}:{token:string,rows:Row[],api:any}){
 const [view,setView]=useState('withdrawals'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[role,setRole]=useState('all');
 const [accountQuery,setAccountQuery]=useState('');
 const [overview,setOverview]=useState<Row>({rows:[],stats:{}}),[accounts,setAccounts]=useState<Row[]>([]),[accountId,setAccountId]=useState(''),[detail,setDetail]=useState<Row|null>(null);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[limit,setLimit]=useState(30),[history,setHistory]=useState('ledger');
 const [operation,setOperation]=useState<'credit'|'withdraw'|'status'|null>(null),[form,setForm]=useState<Row>({}),[saving,setSaving]=useState(false),[formError,setFormError]=useState(''),[revision,setRevision]=useState(0);
 const lastAccount=useRef('');
 const dialog=useRef<HTMLElement|null>(null),priorFocus=useRef<HTMLElement|null>(null),savingRef=useRef(false);
 useEffect(()=>{const id=setTimeout(()=>setAccountQuery(view==='accounts'?query:''),300);return()=>clearTimeout(id)},[query,view]);
 useEffect(()=>{setLimit(30)},[view,query,filter,role]);
 useEffect(()=>{let live=true; const refresh=async()=>{try{const [o,a]=await Promise.all([api('/finance/admin/overview',token),api('/finance/admin/accounts?search='+encodeURIComponent(accountQuery),token)]);if(live){setOverview(o);setAccounts(a);setError('')}}catch(e:any){if(live)setError(displayMessage(e.message))}finally{if(live)setLoading(false)}};refresh();const id=setInterval(refresh,10000);return()=>{live=false;clearInterval(id)}},[token,rows,revision,api,accountQuery]);
 useEffect(()=>{if(!accountId){setDetail(null);return}let live=true;if(lastAccount.current!==accountId){setDetail(null);lastAccount.current=accountId}const refresh=async()=>{try{const d=await api('/finance/admin/accounts/'+accountId,token);if(live)setDetail(d)}catch(e:any){if(live)setError(displayMessage(e.message))}};refresh();const id=setInterval(refresh,10000);return()=>{live=false;clearInterval(id)}},[accountId,token,rows,revision,api]);
 useEffect(()=>{if(!accountId&&!operation)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';priorFocus.current=document.activeElement as HTMLElement;const frame=requestAnimationFrame(()=>dialog.current?.querySelector<HTMLElement>('button,input,textarea')?.focus());const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!savingRef.current){if(operation)setOperation(null);else setAccountId('')}if(e.key==='Tab'){const nodes=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')||[]);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=before;cancelAnimationFrame(frame);document.removeEventListener('keydown',key);priorFocus.current?.focus()}},[accountId,operation]);
 const availableRows=overview.rows.filter((w:Row)=>(role==='all'||w.kind===role)&&(filter==='all'||w.status===filter)&&`${w.user?.name} ${w.user?.email} ${w.id} ${w.pixKey}`.toLowerCase().includes(query.toLowerCase()));
 const availableAccounts=accounts.filter(a=>(role==='all'||a.role===role)&&`${a.id} ${a.name} ${a.email} ${a.phone||''}`.toLowerCase().includes(query.toLowerCase()));
 const start=(mode:'credit'|'withdraw')=>{if(!detail)return;setForm({userId:detail.user.id,amount:'',reason:'',requestId:crypto.randomUUID(),type:'ADJUSTMENT_CREDIT',pixKey:detail.pixKey,pixKeyType:detail.pixKeyType||'EMAIL'});setFormError('');setOperation(mode)};
 const status=(w:Row,next:string)=>{setForm({...w,nextStatus:next,reason:'',reference:'',receiptUrl:''});setFormError('');setOperation('status')};
 const change=(key:string,value:any)=>setForm(f=>({...f,[key]:value}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(savingRef.current)return;savingRef.current=true;setSaving(true);setFormError('');setNotice('');try{const path=operation==='status'?`/finance/admin/withdrawals/${form.kind}/${form.id}`:`/finance/admin/accounts/${form.userId}/${operation==='credit'?'credits':'withdrawals'}`;const body=operation==='status'?{status:form.nextStatus,reason:form.reason,reference:form.reference,receiptUrl:form.receiptUrl}:{amount:Number(form.amount),reason:form.reason,requestId:form.requestId,...(operation==='credit'?{type:form.type}:{pixKey:form.pixKey,pixKeyType:form.pixKeyType})};const result=await api(path,token,operation==='status'?'PATCH':'POST',body);if(!result){setFormError('Não foi possível salvar. Confira a mensagem no painel. O identificador desta operação será mantido para tentar novamente sem duplicar.');return}setOperation(null);setRevision(n=>n+1);setNotice(operation==='credit'?'Crédito registrado na carteira.':operation==='withdraw'?'Saque solicitado e saldo reservado. Nenhum PIX foi enviado automaticamente.':'Status atualizado com registro administrativo.')}catch(e:any){setFormError(displayMessage(e.message))}finally{savingRef.current=false;setSaving(false)}};
 const stats=overview.stats;const pending=(stats.PENDING?.amount||0)+(stats.PROCESSING?.amount||0);
 const field=(key:string,label:string,type='text',props:Row={})=><label>{label}<input type={type} value={form[key]||''} onChange={e=>change(key,e.target.value)} {...props}/></label>;
 const actions=(w:Row)=><div className="financeRowActions">{w.status==='PENDING'&&<button onClick={()=>status(w,'PROCESSING')}>Processar</button>}{w.status==='PROCESSING'&&<button onClick={()=>status(w,'PAID')}><Check size={14}/>Confirmar pagamento</button>}{['PENDING','PROCESSING'].includes(w.status)&&<button className="secondary" onClick={()=>status(w,'REJECTED')}>Rejeitar</button>}</div>;
 return <div className="financeCenter"><div className="financeHeading"><div><small>PORTO PRIME · CENTRAL FINANCEIRA</small><h2>Saques e carteiras</h2><p>Motoboys e parceiros. Cada movimentação com origem, motivo e histórico.</p></div><button onClick={()=>{setView('accounts');setQuery('')}}><Plus size={16}/>Operar uma carteira</button></div>
 <div className="financeMetrics"><div className="primary"><Wallet size={20}/><span>Saldo reservado em saques<strong>{brl(pending)}</strong><small>Aguardando processamento ou pagamento</small></span></div><div><ArrowUpRight size={19}/><span>Repasses confirmados<strong>{brl(stats.PAID?.amount)}</strong><small>{stats.PAID?.count||0} saques pagos</small></span></div><div><History size={19}/><span>Solicitações em aberto<strong>{(stats.PENDING?.count||0)+(stats.PROCESSING?.count||0)}</strong><small>Motoboys e parceiros</small></span></div></div>
 {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="financeNotice" role="status"><Check size={16}/>{notice}</div>}
 <section className="financeSurface"><div className="financeToolbar"><div className="financeTabs"><button aria-pressed={view==='withdrawals'} className={view==='withdrawals'?'active':''} onClick={()=>setView('withdrawals')}>Solicitações</button><button aria-pressed={view==='accounts'} className={view==='accounts'?'active':''} onClick={()=>setView('accounts')}>Carteiras</button></div><label className="financeSearch"><Search size={17}/><input aria-label="Buscar na central financeira" placeholder={view==='withdrawals'?'Nome, chave PIX ou número do saque':'Nome, e-mail ou telefone'} value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Tipo de conta" value={role} onChange={e=>setRole(e.target.value)}><option value="all">Todas as contas</option><option value="COURIER">Motoboys</option><option value="PARTNER">Parceiros</option></select>{view==='withdrawals'&&<select aria-label="Status do saque" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos os status</option>{['PENDING','PROCESSING','PAID','REJECTED','CANCELED'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select>}</div>
 {loading?<div className="financeSkeleton" aria-label="Carregando carteiras"/>:view==='withdrawals'?<><div className="financeCaption">{availableRows.length} solicitações na lista · até 200 mais recentes; totais acima abrangem todo o histórico</div><div className="financeWithdrawalList">{availableRows.slice(0,limit).map((w:Row)=><article key={w.kind+w.id}><div className="financeWithdrawalIdentity"><span className="financeAvatar">{w.user?.name?.[0]||'P'}</span><div><button className="financeName" onClick={()=>setAccountId(w.user.id)}>{w.user?.name}<ChevronRight size={13}/></button><small>{w.kind==='PARTNER'?'Parceiro':'Motoboy'} · {when(w.requestedAt)}</small><span className="financePix">{w.pixKeyType} · {w.pixKey}</span><small title={w.id}>Saque #{w.id.slice(-8).toUpperCase()}</small></div></div><div className="financeWithdrawalValue"><strong>{brl(w.amount)}</strong><Status value={w.status}/></div>{actions(w)}</article>)}</div>{!availableRows.length&&<div className="financeEmpty"><Wallet size={32}/><h3>Nenhum saque encontrado</h3><p>Solicitações e repasses aparecem aqui, com os filtros escolhidos.</p></div>}</>:<><div className="financeCaption">Selecione uma conta para consultar e operar. Até 200 resultados; a busca consulta todas as contas da plataforma.</div><div className="financeAccountList">{availableAccounts.slice(0,limit).map(a=><button key={a.id} onClick={()=>{setAccountId(a.id);setHistory('ledger')}}><span className="financeAvatar">{a.name?.[0]}</span><span><strong>{a.name}</strong><small>{a.role==='PARTNER'?'Parceiro':'Motoboy'} · {a.email}</small></span><ChevronRight size={18}/></button>)}</div>{!availableAccounts.length&&<div className="financeEmpty"><Wallet size={32}/><h3>Nenhuma conta encontrada</h3></div>}</>}
 {(view==='withdrawals'?availableRows.length:availableAccounts.length)>limit&&<button className="secondary financeMore" onClick={()=>setLimit(n=>n+30)}>Mostrar mais</button>}</section>
 {accountId&&!operation&&<div className="financeBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setAccountId('')}}><section ref={dialog} className="financeDrawer" role="dialog" aria-modal="true" aria-labelledby="finance-account-title"><div className="financeDialogHead"><div><small>CARTEIRA · {detail?.user.role==='PARTNER'?'PARCEIRO':'MOTOBOY'}</small><h2 id="finance-account-title">{detail?.user.name||'Consultando conta…'}</h2><span>{detail?.user.email}</span></div><button className="secondary" aria-label="Fechar carteira" onClick={()=>setAccountId('')}><X size={19}/></button></div>{!detail?error?<div className="error" role="alert">{error}</div>:<div className="financeSkeleton"/>:<><div className="financeBalance"><span>Saldo disponível</span><strong>{brl(detail.availableBalance)}</strong><small>{brl(detail.pendingWithdrawals)} reservado em saques</small><div><button onClick={()=>start('credit')}><Plus size={16}/>Creditar saldo</button><button className="secondary" onClick={()=>start('withdraw')}><ArrowUpRight size={16}/>Solicitar saque</button></div></div><div className="financeAccountTotals"><div><small>Total creditado</small><strong>{brl(detail.totalCredited)}</strong></div><div><small>Saques pagos · {detail.paidCount}</small><strong>{brl(detail.paidTotal)}</strong></div></div><div className="financePixBox"><ShieldCheck size={19}/><span><small>PIX cadastrado</small><b>{detail.pixKey?`${detail.pixKeyType} · ${detail.pixKey}`:'Sem chave cadastrada — informe no saque'}</b></span></div><div className="financeHistoryTabs">{[['ledger','Movimentações'],['withdrawals','Saques'],['audit','Registro administrativo']].map(([key,label])=><button aria-pressed={history===key} className={history===key?'active':''} key={key} onClick={()=>setHistory(key)}>{label}</button>)}</div>
 {history==='ledger'&&<div className="financeLedger">{detail.entries.map((e:Row)=><article key={e.id}><span className={Number(e.amount)>=0?'credit':'debit'}>{Number(e.amount)>=0?<ArrowDownLeft size={18}/>:<ArrowUpRight size={18}/>}</span><div><b>{labels[e.type]||e.type}</b><p>{e.description}</p><small>{when(e.createdAt)}{e.metadata?.actorName?` · ${e.metadata.actorName}`:''}</small></div><strong className={Number(e.amount)>=0?'creditText':''}>{Number(e.amount)>0?'+ ':''}{brl(e.amount)}</strong></article>)}{!detail.entries.length&&<p className="financeEmptyText">Nenhuma movimentação registrada.</p>}</div>}
 {history==='withdrawals'&&<div className="financeDetailWithdrawals">{detail.withdrawals.map((w:Row)=><article key={w.id}><div><b>{brl(w.amount)}</b><small>{when(w.requestedAt)}</small>{w.processedAt&&<small>Finalizado em {when(w.processedAt)}</small>}<p>{w.pixKeyType} · {w.pixKey}</p>{w.receiptUrl&&<a href={w.receiptUrl} target="_blank" rel="noopener noreferrer">Abrir comprovante</a>}</div><Status value={w.status}/>{actions({...w,kind:detail.user.role,user:detail.user})}</article>)}{!detail.withdrawals.length&&<p className="financeEmptyText">Nenhum saque solicitado.</p>}</div>}
 {history==='audit'&&<div className="financeAudit">{detail.audit.map((a:Row)=><article key={a.id}><b>{labels[a.action]||a.action} · {brl(a.amount)}</b><p>{a.reason}</p><small>{when(a.createdAt)} · {a.actorName||a.actorId}</small>{a.reference&&<p>Referência: {a.reference}</p>}</article>)}{!detail.audit.length&&<p className="financeEmptyText">Nenhuma operação administrativa nesta central.</p>}</div>}<p className="financeFootnote">Histórico: até 100 registros por seção. O saldo considera todas as movimentações disponíveis.</p></>}</section></div>}
 {operation&&<div className="financeBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setOperation(null)}}><section ref={dialog} className="financeOperation" role="dialog" aria-modal="true" aria-labelledby="finance-operation-title"><div className="financeDialogHead"><div><small>OPERAÇÃO REGISTRADA</small><h2 id="finance-operation-title">{operation==='credit'?'Creditar carteira':operation==='withdraw'?'Solicitar saque':form.nextStatus==='PAID'?'Confirmar pagamento':form.nextStatus==='REJECTED'?'Rejeitar e estornar':'Iniciar processamento'}</h2><span>{operation==='status'?form.user?.name:detail?.user.name}</span></div><button className="secondary" disabled={saving} aria-label="Fechar operação" onClick={()=>setOperation(null)}><X size={19}/></button></div><form onSubmit={submit}>{operation==='status'?<div className="financeOperationAmount">{brl(form.amount)} <Status value={form.status}/></div>:field('amount','Valor (R$)','number',{min:'.01',max:operation==='withdraw'?detail?.availableBalance:99999999.99,step:'.01',required:true})}{operation==='credit'&&<label>Tipo de crédito<select value={form.type} onChange={e=>change('type',e.target.value)}><option value="ADJUSTMENT_CREDIT">Crédito administrativo</option><option value="BONUS_CREDIT">Bônus</option></select></label>}{operation==='withdraw'&&<><div className="financeFormHint">Disponível: <b>{brl(detail?.availableBalance)}</b>. O valor será reservado; o PIX deve ser realizado separadamente.</div><label>Tipo de chave PIX<select value={form.pixKeyType} onChange={e=>change('pixKeyType',e.target.value)}>{['CPF','CNPJ','EMAIL','PHONE','RANDOM'].map(v=><option key={v}>{v}</option>)}</select></label>{field('pixKey','Chave PIX','text',{required:true,maxLength:250})}</>}
 <label>Motivo obrigatório<textarea required minLength={3} maxLength={500} value={form.reason||''} onChange={e=>change('reason',e.target.value)} placeholder="Descreva a solicitação e a origem desta operação"/></label>{operation==='status'&&form.nextStatus==='PAID'&&<>{field('reference','Referência / identificador do pagamento','text',{required:true,minLength:3,maxLength:120})}{field('receiptUrl','Comprovante hospedado (opcional)','url',{pattern:'https://.*',maxLength:2048})}<div className="financeFormHint">Confirme somente após realizar e verificar o PIX. Esta ação registra o repasse; não envia dinheiro.</div></>}{operation==='status'&&form.nextStatus==='REJECTED'&&<div className="financeFormHint">O valor reservado será devolvido à carteira uma única vez.</div>}{formError&&<div className="error" role="alert">{formError}</div>}<div className="financeOperationActions"><button type="button" className="secondary" disabled={saving} onClick={()=>setOperation(null)}>Cancelar</button><button disabled={saving}>{saving?'Registrando…':'Confirmar operação'}</button></div></form></section></div>}
 </div>;
}
