"use client";
import {useMemo,useState} from 'react';
import {Archive,Search,ChevronDown,ArrowDownLeft,Ticket,ShieldCheck,XCircle} from 'lucide-react';
import OrderAvailabilityEditor from './order-availability-editor';
import './order-archive.css';
type Row=Record<string,any>;
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=(v:any)=>v?new Date(v).toLocaleString('pt-BR'):'—';
export function isArchivedOrder(o:Row){return o.status==='CANCELED'||o.paymentStatus==='REFUNDED'||(['DELIVERED'].includes(o.status)&&(o.paymentStatus==='PARTIALLY_REFUNDED'||Number(o.refundedTotal)>0||Number(o.creditedTotal)>0));}
const refunded=(o:Row)=>o.paymentStatus==='REFUNDED'||o.paymentStatus==='PARTIALLY_REFUNDED'||Number(o.refundedTotal)>0;
const credited=(o:Row)=>Number(o.creditedTotal)>0;
export default function OrderArchive({orders,request,reload}:{orders:Row[],request:(path:string,method:string,body?:any)=>Promise<any>,reload:()=>void}){
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[until,setUntil]=useState(''),[page,setPage]=useState(1);
 const archive=useMemo(()=>orders.filter(isArchivedOrder).sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()),[orders]);
 const results=useMemo(()=>{const q=query.trim().replace(/^#/,'').toLocaleLowerCase('pt-BR');return archive.filter(o=>{const created=new Date(o.createdAt).getTime();return (filter==='all'||filter==='canceled'&&o.status==='CANCELED'||filter==='refund'&&refunded(o)||filter==='credit'&&credited(o))&&(!q||[o.id,o.customer?.name,o.customer?.email,o.customer?.phone,...(o.items||[]).map((i:Row)=>i.productName)].some(v=>String(v||'').toLocaleLowerCase('pt-BR').includes(q)))&&(!from||created>=new Date(from+'T00:00:00').getTime())&&(!until||created<=new Date(until+'T23:59:59.999').getTime());});},[archive,filter,query,from,until]);
 const pages=Math.max(1,Math.ceil(results.length/15)),currentPage=Math.min(page,pages),visible=results.slice((currentPage-1)*15,currentPage*15);
 const sections=[{id:'all',label:'Todos os arquivos',count:archive.length,icon:Archive},{id:'canceled',label:'Cancelados',count:archive.filter(o=>o.status==='CANCELED').length,icon:XCircle},{id:'refund',label:'Reembolsados',count:archive.filter(refunded).length,icon:ArrowDownLeft},{id:'credit',label:'Vouchers e créditos',count:archive.filter(credited).length,icon:Ticket}];
 return <section className="orderArchive"><div className="archiveHero"><span className="archiveHeroIcon"><Archive size={26}/></span><div><small>HISTÓRICO PRESERVADO</small><h2>Cada pedido, no lugar certo.</h2><p>Cancelamentos, devoluções e créditos organizados em uma única central.</p></div><span className="archiveSecurity"><ShieldCheck size={16}/> Registro financeiro protegido</span></div>
 <nav className="archiveSections" aria-label="Divisões do arquivo">{sections.map(s=><button key={s.id} aria-pressed={filter===s.id} className={filter===s.id?'selected':''} onClick={()=>{setFilter(s.id);setPage(1);}}><s.icon size={19}/><span>{s.label}</span><b>{s.count}</b></button>)}</nav>
 <div className="archiveToolbar"><label className="archiveSearch"><Search size={18}/><input aria-label="Buscar pedido no arquivo" placeholder="Número do pedido, cliente, telefone ou produto…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><label>De<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label>Até<input type="date" min={from||undefined} value={until} onChange={e=>{setUntil(e.target.value);setPage(1);}}/></label>{(query||from||until)&&<button onClick={()=>{setQuery('');setFrom('');setUntil('');setPage(1);}}>Limpar</button>}</div>
 <div className="archiveResultHeading"><strong>{results.length} {results.length===1?'registro encontrado':'registros encontrados'}</strong><span>Pedidos com devolução parcial continuam na operação até a entrega.</span></div>
 {!visible.length?<div className="archiveEmpty"><Archive size={36}/><h3>{archive.length?'Nenhum registro para estes filtros':'Seu arquivo está organizado'}</h3><p>{archive.length?'Busque outro número ou ajuste o período.':'Pedidos cancelados ou reembolsados aparecerão aqui automaticamente.'}</p></div>:<div className="archiveList">{visible.map(o=><details className="archiveRecord" key={o.id}><summary><div className="archiveIdentity"><span className="archiveRecordIcon">{credited(o)?<Ticket size={18}/>:refunded(o)?<ArrowDownLeft size={18}/>:<XCircle size={18}/>}</span><div><strong>#{o.id.slice(-8).toUpperCase()}</strong><small>{o.customer?.name||'Cliente'} · {date(o.createdAt)}</small></div></div><div className="archiveBadges">{o.status==='CANCELED'&&<span>Cancelado</span>}{refunded(o)&&<span className="refund">{o.paymentStatus==='REFUNDED'?'Reembolso integral':'Reembolso'}</span>}{credited(o)&&<span className="credit">Crédito emitido</span>}</div><div className="archiveAmount"><strong>{money(o.total)}</strong><small>Valor pago do pedido</small></div><ChevronDown size={18}/></summary><div className="archiveRecordBody"><div className="archiveFacts"><div><small>CLIENTE</small><strong>{o.customer?.name||'—'}</strong><span>{o.customer?.email}</span><span>{o.customer?.phone}</span></div><div><small>ENDEREÇO</small><strong>{o.address?.street||'—'}, {o.address?.number||'s/n'}</strong><span>{o.address?.neighborhood} · {o.address?.city}</span></div><div><small>REGISTRO</small><strong>Pedido #{o.id}</strong><span>Cancelamento: {date(o.canceledAt)}</span><span>Atualizado: {date(o.updatedAt)}</span></div></div><div className="archiveMoney"><div><span>Pagamento original</span><strong>{money(o.total)}</strong></div><div><span>Reembolsado no pagamento</span><strong>{money(o.refundedTotal)}</strong></div><div><span>Crédito / voucher emitido</span><strong>{money(o.creditedTotal)}</strong></div></div><OrderAvailabilityEditor order={o} products={[]} request={request} reload={reload}/><footer><ShieldCheck size={15}/><span>Registro preservado. Reembolsos pendentes podem ser consultados nos itens acima.</span></footer></div></details>)}</div>}
 <footer className="archivePagination"><span>Página {currentPage} de {pages} · até 15 pedidos por página</span><div><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Anterior</button><button disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Próxima</button></div></footer></section>;
}
