"use client";
import {useState} from 'react';
import {AlertTriangle,CheckCircle2,ArrowRightLeft,Undo2} from 'lucide-react';
import './order-availability.css';
type Row=Record<string,any>;
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const labels:Record<string,string>={AVAILABLE:'Disponível',AWAITING_CUSTOMER:'Aguardando cliente',REPLACED:'Substituição confirmada',REFUND_PROCESSING:'Item removido · reembolso em processamento',REFUNDED:'Item removido · reembolso confirmado',VOUCHERED:'Item removido · crédito no Cartão Porto Prime'};
export default function OrderAvailabilityEditor({order,products,request,reload}:{order:Row,products:Row[],request:(path:string,method:string,body?:any)=>Promise<any>,reload:()=>void}){
 const [editing,setEditing]=useState<Row|null>(null),[note,setNote]=useState(''),[alternatives,setAlternatives]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const eligible=order.paymentStatus==='PAID'&&!order.courierId&&['PENDING','CONFIRMED','PREPARING','READY_FOR_PICKUP'].includes(order.status);
 async function action(item:Row,unavailable:boolean){setBusy(true);setError('');try{await request(`/admin/orders/${order.id}/items/${item.id}/availability`,'PATCH',{unavailable,note,alternativeIds:alternatives});setEditing(null);reload();}catch(e:any){setError(e.message||'Não foi possível atualizar. Tente novamente.');}finally{setBusy(false);}}
 async function retry(item:Row){setBusy(true);try{await request(`/admin/orders/${order.id}/items/${item.id}/refund-retry`,'POST');reload();}catch(e:any){setError(e.message||'Não foi possível consultar o reembolso.');}finally{setBusy(false);}}
 return <section className="availabilityEditor">{order.fulfillmentHold&&<div className="availabilityWarning"><AlertTriangle size={20}/><div><strong>Pedido pausado · decisão do cliente</strong><p>O cliente foi avisado. A liberação permanece bloqueada até a resolução dos itens abaixo.</p></div></div>}{!order.fulfillmentHold&&(order.items||[]).some((i:Row)=>i.availabilityStatus==='REFUND_PROCESSING')&&<div className="availabilityProgress"><CheckCircle2 size={20}/><div><strong>{order.status==='CANCELED'?'Pedido cancelado · devolução em acompanhamento':'Produtos restantes podem seguir'}</strong><p>{order.status==='CANCELED'?'Todos os itens foram removidos. Confira a confirmação do reembolso abaixo.':'O cliente confirmou a remoção. O reembolso é acompanhado separadamente e não bloqueia o despacho.'}</p></div></div>}{error&&<p role="alert" className="availabilityError">{error}</p>}
 {(order.items||[]).map((item:Row)=>{const status=item.availabilityStatus||'AVAILABLE';return <div className={"availabilityItem "+(['REFUND_PROCESSING','REFUNDED','VOUCHERED'].includes(status)?"availabilityRemoved":"")} key={item.id}><div className="availabilityItemHeading"><div><small>{item.quantity} UNIDADE(S)</small><strong>{item.productName}</strong><span>{labels[status]||status}</span></div><b>{money(item.total)}</b></div>{item.originalProductName&&status==='REPLACED'&&<p>Substitui {item.originalProductName}</p>}{item.availabilityNote&&status==='AWAITING_CUSTOMER'&&<p>{item.availabilityNote}</p>}<div className="availabilityActions">{eligible&&['AVAILABLE','REPLACED'].includes(status)&&<button className="secondary" disabled={busy} onClick={()=>{setEditing(item);setNote('');setAlternatives([]);setError('');}}><ArrowRightLeft size={16}/> Informar indisponibilidade</button>}{eligible&&status==='AWAITING_CUSTOMER'&&<button className="secondary" disabled={busy} onClick={()=>action(item,false)}><Undo2 size={16}/> Restaurar disponibilidade</button>}{status==='REFUND_PROCESSING'&&<button className="secondary" disabled={busy} onClick={()=>retry(item)}>Verificar / tentar reembolso</button>}{['REFUNDED','VOUCHERED'].includes(status)&&<span><CheckCircle2 size={15}/> {money(Number(item.refundAmount||0)+Number(item.creditAmount||0))} resolvidos</span>}</div></div>;})}
 {(Number(order.refundedTotal)>0||Number(order.creditedTotal)>0)&&<footer className="availabilityTotals"><span>Devolvido no pagamento <b>{money(order.refundedTotal)}</b></span><span>Crédito para o cliente <b>{money(order.creditedTotal)}</b></span></footer>}
 {editing&&<div className="availabilityModalBackdrop"><section className="availabilityModal" role="dialog" aria-modal="true" aria-labelledby="availability-title"><header><small>ATENDIMENTO DO PEDIDO</small><h2 id="availability-title">Um cuidado com cada item.</h2><p>Informe a indisponibilidade de <strong>{editing.productName}</strong>. O cliente poderá escolher substituição, reembolso ou voucher.</p></header><label>Mensagem ao cliente<textarea maxLength={500} value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex.: o estoque deste produto acabou. Selecionamos alternativas para você."/></label><h3>Alternativas pelo mesmo preço</h3><p>Selecione até oito produtos disponíveis. Nenhuma cobrança adicional.</p><div className="availabilityAlternatives">{products.filter(p=>p.id!==editing.productId&&p.active&&!p.archived&&Number(p.stock)>=editing.quantity&&Math.round(Number(p.price)*100)===Math.round(Number(editing.unitPrice)*100)).map(p=><label key={p.id}><input type="checkbox" checked={alternatives.includes(p.id)} disabled={busy||(!alternatives.includes(p.id)&&alternatives.length>=8)} onChange={e=>setAlternatives(e.target.checked?[...alternatives,p.id]:alternatives.filter(id=>id!==p.id))}/><span>{p.name}<small>{money(p.price)}</small></span></label>)}</div>{error&&<p role="alert" className="availabilityError">{error}</p>}<footer><button className="secondary" disabled={busy} onClick={()=>setEditing(null)}>Cancelar</button><button disabled={busy} onClick={()=>action(editing,true)}>{busy?'Enviando…':'Avisar cliente e pausar pedido'}</button></footer></section></div>}</section>;
}
