import {describe,it,expect,vi} from 'vitest';
vi.mock('../prisma/prisma.service.js',()=>({PrismaService:class{}}));
vi.mock('../auth/auth.service.js',()=>({AuthService:class{}}));
vi.mock('../realtime/realtime.gateway.js',()=>({RealtimeGateway:class{}}));
import {FinanceService} from './finance.service.js';
const nonce='00000000-0000-4000-8000-000000000001';
function fixture(role='ADMIN'){
 const users:any={c:{id:'c',name:'Courier',email:'c@example.test',role:'COURIER',status:'ACTIVE',courierProfile:{id:'cp',pixKey:'c@example.test',pixKeyType:'EMAIL'}},p:{id:'p',name:'Partner',email:'p@example.test',role:'PARTNER',status:'ACTIVE',partnerProfile:{id:'pp',onboardingData:{pixKey:'p@example.test',pixKeyType:'EMAIL'}}},customer:{id:'customer',role:'CUSTOMER'}};
 const entries:any[]=[{id:'initial',courierId:'cp',type:'DELIVERY_CREDIT',amount:50}],partnerEntries:any[]=[{id:'pinitial',userId:'p',type:'BONUS_CREDIT',amount:30}],withdrawals:any[]=[],partnerWithdrawals:any[]=[],audit:any[]=[];
 const matches=(row:any,where:any)=>Object.entries(where||{}).every(([k,v]:any)=>k==='availableAt'||row[k]===v);
 const ledger=(list:any[])=>({aggregate:vi.fn(async({where}:any)=>({_sum:{amount:list.filter(e=>matches(e,where)).reduce((n,e)=>n+Number(e.amount),0)}})),findUnique:vi.fn(async({where}:any)=>list.find(e=>e.idempotencyKey===where.idempotencyKey)),findMany:vi.fn(async({where}:any)=>list.filter(e=>matches(e,where))),create:vi.fn(async({data}:any)=>{const e={id:'e'+list.length,...data};list.push(e);return e}),upsert:vi.fn(async({where,create}:any)=>{let e=list.find(e=>e.idempotencyKey===where.idempotencyKey);if(!e){e={id:'e'+list.length,...create};list.push(e)}return e})});
 const payout=(list:any[])=>({create:vi.fn(async({data}:any)=>{list.push(data);return data}),findUnique:vi.fn(async({where}:any)=>list.find(w=>w.id===where.id)),update:vi.fn(async({where,data}:any)=>Object.assign(list.find(w=>w.id===where.id),data)),findMany:vi.fn(async()=>list),aggregate:vi.fn(async()=>({_sum:{amount:0}})),groupBy:vi.fn(async()=>[])});
 const db:any={user:{findUnique:vi.fn(async({where}:any)=>users[where.id]),findMany:vi.fn(async()=>Object.values(users))},courierProfile:{findUnique:vi.fn(async()=>({userId:'c'}))},$queryRawUnsafe:vi.fn(async()=>[]),courierLedgerEntry:ledger(entries),partnerLedgerEntry:ledger(partnerEntries),withdrawal:payout(withdrawals),partnerWithdrawal:payout(partnerWithdrawals),financialAudit:{create:vi.fn(async({data}:any)=>{audit.push(data);return data}),findMany:vi.fn(async()=>audit)}};
 db.$transaction=async(fn:any)=>{const snapshots=[entries,partnerEntries,withdrawals,partnerWithdrawals,audit].map(list=>structuredClone(list));try{return await fn(db)}catch(e){[entries,partnerEntries,withdrawals,partnerWithdrawals,audit].forEach((list,i)=>list.splice(0,list.length,...snapshots[i]));throw e}};
 const realtime:any={emitToUser:vi.fn(),emitToRole:vi.fn()};const actor={id:role==='PARTNER'?'p':'admin',role,name:'Operator'};
 return{service:new FinanceService(db,{authenticate:async()=>actor} as any,realtime),db,entries,partnerEntries,withdrawals,partnerWithdrawals,audit,realtime};
}
const credit={amount:10,reason:'Ajuste solicitado',requestId:nonce};
const withdrawal={amount:20,reason:'Saque solicitado pela equipe',requestId:nonce};
describe('Administrative and partner finance',()=>{
 it('requires admin before any credit or third-party withdrawal',async()=>{const f=fixture('PARTNER');await expect(f.service.credit('c',credit)).rejects.toThrow('administrador');await expect(f.service.withdraw('c',withdrawal)).rejects.toThrow('administrador');expect(f.db.user.findUnique).not.toHaveBeenCalled()});
 it('refuses customer accounts as a financial target',async()=>{const f=fixture();await expect(f.service.credit('customer',credit)).rejects.toThrow('Conta');expect(f.audit).toHaveLength(0)});
 it.each([0,-1,0.001,Infinity,100000000])('rejects invalid money %s',async amount=>{const f=fixture();await expect(f.service.credit('c',{...credit,amount})).rejects.toThrow('valor positivo');expect(f.entries).toHaveLength(1)});
 it('requires a reason and stable request identifier',async()=>{const f=fixture();await expect(f.service.credit('c',{...credit,reason:''})).rejects.toThrow('Motivo');await expect(f.service.credit('c',{...credit,requestId:'bad'})).rejects.toThrow('Identificador')});
 it('credits courier once on retry and records the authenticated operator',async()=>{const f=fixture();await f.service.credit('c',credit);await f.service.credit('c',credit);expect(f.entries).toHaveLength(2);expect(f.entries[1]).toMatchObject({courierId:'cp',amount:10,type:'ADJUSTMENT_CREDIT',metadata:{actorId:'admin',actorName:'Operator'}});expect(f.audit).toHaveLength(1);expect(f.db.$queryRawUnsafe.mock.calls[0]).toEqual(['SELECT "id" FROM "CourierProfile" WHERE "id" = $1 FOR UPDATE','cp']);expect(f.realtime.emitToUser).toHaveBeenCalledWith('c','wallet.updated',expect.any(Object))});
 it('rejects reuse of request identifier with a different credit amount',async()=>{const f=fixture();await f.service.credit('c',credit);await expect(f.service.credit('c',{...credit,amount:15})).rejects.toThrow('identificador');expect(f.entries).toHaveLength(2)});
 it('credits partner separately without modifying courier funds',async()=>{const f=fixture();await f.service.credit('p',{...credit,type:'BONUS_CREDIT'});expect(f.partnerEntries[1]).toMatchObject({userId:'p',amount:10,type:'BONUS_CREDIT'});expect(f.entries).toHaveLength(1)});
 it('reserves a courier withdrawal once using registration PIX and immutable snapshot',async()=>{const f=fixture();const first=await f.service.withdraw('c',withdrawal),second=await f.service.withdraw('c',withdrawal);expect(second.id).toBe(first.id);expect(f.withdrawals).toHaveLength(1);expect(f.entries[1]).toMatchObject({amount:-20,type:'WITHDRAWAL_DEBIT'});expect(first).toMatchObject({status:'PENDING',pixKey:'c@example.test'});expect(f.audit).toHaveLength(1)});
 it('rejects overdraw and malformed PIX without creating a reservation',async()=>{const f=fixture();await expect(f.service.withdraw('c',{...withdrawal,amount:51})).rejects.toThrow('Saldo');await expect(f.service.withdraw('c',{...withdrawal,pixKey:'11111111111',pixKeyType:'CPF'})).rejects.toThrow('Confira');expect(f.withdrawals).toHaveLength(0);expect(f.entries).toHaveLength(1)});
 it('partner can request own withdrawal but not another account',async()=>{const f=fixture('PARTNER');await f.service.myWithdrawal({amount:10,requestId:nonce});expect(f.partnerWithdrawals[0]).toMatchObject({userId:'p',amount:10,pixKey:'p@example.test'});await expect(f.service.withdraw('c',{amount:10,requestId:nonce},undefined,true)).rejects.toThrow('sua carteira')});
 it('rejects payment confirmation without prior processing or reference',async()=>{const f=fixture();const w=await f.service.withdraw('c',withdrawal);await expect(f.service.status('COURIER',w.id,{status:'PAID',reason:'Confirmado',reference:'PIX-123'})).rejects.toThrow('processamento');await f.service.status('COURIER',w.id,{status:'PROCESSING',reason:'Iniciar repasse'});await expect(f.service.status('COURIER',w.id,{status:'PAID',reason:'Confirmado',reference:''})).rejects.toThrow('Referência');expect(f.withdrawals[0].status).toBe('PROCESSING')});
 it('confirms paid withdrawal without debiting again and preserves audit reference',async()=>{const f=fixture();const w=await f.service.withdraw('c',withdrawal);await f.service.status('COURIER',w.id,{status:'PROCESSING',reason:'Iniciar repasse'});await f.service.status('COURIER',w.id,{status:'PAID',reason:'Repasse conferido',reference:'PIX-123',receiptUrl:'https://receipts.example.test/r'});expect(f.entries).toHaveLength(2);expect(f.audit.at(-1)).toMatchObject({action:'PAID',reference:'PIX-123',actorId:'admin'});const count=f.audit.length;await f.service.status('COURIER',w.id,{status:'PAID',reason:'Repasse conferido',reference:'PIX-123'});expect(f.audit).toHaveLength(count);await expect(f.service.status('COURIER',w.id,{status:'REJECTED',reason:'Tentar reverter'})).rejects.toThrow('encerrado')});
 it('rejection returns partner balance exactly once',async()=>{const f=fixture();const w=await f.service.withdraw('p',withdrawal);await f.service.status('PARTNER',w.id,{status:'REJECTED',reason:'Chave do beneficiário incorreta'});await f.service.status('PARTNER',w.id,{status:'REJECTED',reason:'Chave do beneficiário incorreta'});expect(f.partnerEntries).toHaveLength(3);expect(f.partnerEntries[2]).toMatchObject({type:'REVERSAL',amount:20});expect(await f.service.detail('p')).toMatchObject({availableBalance:30})});
 it('rolls back credit and audit together when audit persistence fails',async()=>{const f=fixture();f.db.financialAudit.create.mockRejectedValue(new Error('audit unavailable'));await expect(f.service.credit('c',credit)).rejects.toThrow('audit unavailable');expect(f.entries).toHaveLength(1);expect(f.realtime.emitToUser).not.toHaveBeenCalled()});
 it('does not leak complete onboarding data or admin audit to partner self-service',async()=>{const f=fixture('PARTNER');const d=await f.service.mine();expect(d.user).not.toHaveProperty('partnerProfile');expect(d.audit).toEqual([]);await expect(f.service.detail('c',undefined,true)).rejects.toThrow('sua carteira')});
});
