import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../state/app_state.dart';

class CustomerCreditSelector extends StatelessWidget {
 const CustomerCreditSelector({super.key,this.available});
 final double? available;
 String money(double v)=>'R\$ ${v.toStringAsFixed(2).replaceAll('.',',')}';
 Future<void> edit(BuildContext context,double maximum,double selected)async{
  final controller=TextEditingController(text:(selected>0?selected:maximum).toStringAsFixed(2).replaceAll('.',','));
  String? error;
  final amount=await showModalBottomSheet<double>(context:context,isScrollControlled:true,showDragHandle:true,backgroundColor:Colors.white,shape:const RoundedRectangleBorder(borderRadius:BorderRadius.vertical(top:Radius.circular(26))),builder:(sheet)=>StatefulBuilder(builder:(sheet,setState)=>SafeArea(child:SingleChildScrollView(padding:EdgeInsets.fromLTRB(24,8,24,24+MediaQuery.viewInsetsOf(sheet).bottom),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.credit_card_rounded,color:Color(0xFF1C806A),size:32),const SizedBox(height:16),const Text('Quanto deseja usar?',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800,color:Color(0xFF173E48))),const SizedBox(height:10),Text('Você pode usar até ${money(maximum)} em produtos. O restante fica no cartão.',style:const TextStyle(height:1.6,color:Color(0xFF637B84))),const SizedBox(height:20),TextField(controller:controller,autofocus:true,keyboardType:const TextInputType.numberWithOptions(decimal:true),inputFormatters:[FilteringTextInputFormatter.allow(RegExp(r'[0-9.,]'))],decoration:InputDecoration(labelText:'Valor do voucher',prefixText:'R\$ ',errorText:error,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14)))),const SizedBox(height:20),SizedBox(width:double.infinity,child:FilledButton(onPressed:(){final raw=controller.text.trim();final value=double.tryParse(raw.replaceAll(',','.'));if(!RegExp(r'^\d+(?:[.,]\d{0,2})?$').hasMatch(raw)||value==null||value<=0||value>maximum){setState(()=>error='Informe um valor entre R\$ 0,01 e ${money(maximum)}.');return;}Navigator.pop(sheet,(value*100).round()/100);},child:const Padding(padding:EdgeInsets.symmetric(vertical:14),child:Text('Usar este valor')))),TextButton(onPressed:()=>Navigator.pop(sheet),child:const Text('Voltar'))])))));
  controller.dispose();
  if(amount!=null)AppState.instance.chooseCustomerCredit(true,amount:amount);
 }
 @override Widget build(BuildContext context)=>AnimatedBuilder(animation:AppState.instance,builder:(context,_){final app=AppState.instance;final balance=available??app.customerCreditBalance;final maxCredit=min(balance,app.cartSubtotal);final selected=app.selectedCustomerCredit(balance);
  if(!app.isCustomer||balance<=0||app.cart.isEmpty)return const SizedBox.shrink();
  return Container(margin:const EdgeInsets.only(bottom:16,top:12),padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:app.useCustomerCredit?const Color(0xFFEAF6EF):Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:app.useCustomerCredit?const Color(0xFF9DCAB4):const Color(0xFFDCE7E8))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:const Color(0xFF1B6F62),borderRadius:BorderRadius.circular(12)),child:const Icon(Icons.credit_card_rounded,color:Colors.white,size:22)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Usar saldo Porto Prime',style:TextStyle(fontWeight:FontWeight.w800,fontSize:15)),const SizedBox(height:5),Text('${money(balance)} disponíveis',style:const TextStyle(fontSize:12,color:Color(0xFF587A70)))])),Switch(value:app.useCustomerCredit,onChanged:maxCredit<=0?null:(value)=>app.chooseCustomerCredit(value,amount:value?maxCredit:0))]),const SizedBox(height:12),Text(app.useCustomerCredit?'Você escolheu ${money(selected)}. O restante dos produtos e a entrega serão pagos pelo Stripe.':'Use nesta compra se quiser. Sem ativar, seu saldo permanece guardado no cartão.',style:const TextStyle(fontSize:12,height:1.6,color:Color(0xFF5F7780))),if(app.useCustomerCredit)Align(alignment:Alignment.centerLeft,child:TextButton.icon(onPressed:()=>edit(context,maxCredit,selected),icon:const Icon(Icons.edit_outlined,size:17),label:const Text('Alterar valor utilizado')))]));});
}
