import {describe,it,expect,vi} from 'vitest';
vi.mock('../prisma/prisma.service.js',()=>({PrismaService:class{}}));
vi.mock('../auth/auth.service.js',()=>({AuthService:class{}}));
vi.mock('../realtime/realtime.gateway.js',()=>({RealtimeGateway:class{}}));
import {ItemAvailabilityService} from './item-availability.service.js';
import {allocateCredit,settlementAmounts} from './customer-credit.js';
function fixture(role='CUSTOMER'){
 const item:any={id:'i',orderId:'o',productId:'p',productName:'Gin',quantity:1,unitPrice:20,total:20,storeCreditShare:5,availabilityStatus:'AWAITING_CUSTOMER',issueId:'unique',refundAttempt:0,availabilityOptions:[{id:'q'}]};
 const order:any={id:'o',customerId:'u',status:'PREPARING',paymentStatus:'PAID',deliveryFee:5.5,total:20.5,stripePaymentIntentId:'pi_test',items:[item],refundedTotal:0,creditedTotal:0};item.order=order;
 const db:any={$queryRawUnsafe:vi.fn(),order:{findUnique:vi.fn(async()=>order),update:vi.fn(async({data}:any)=>{for(const[k,v]of Object.entries(data))order[k]=typeof v==='object'&&v!==null&&'increment'in v?Number(order[k]||0)+(v as any).increment:v;return order;})},orderItem:{findUnique:vi.fn(async()=>item),update:vi.fn(async({data}:any)=>{Object.assign(item,data);return item;})},product:{findFirst:vi.fn(async()=>({id:'q',name:'Outro gin',price:20})),findMany:vi.fn(async()=>[])},customerCreditEntry:{upsert:vi.fn(async()=>({})),aggregate:vi.fn(async()=>({_sum:{amount:0}}))}};db.$transaction=async(fn:any)=>fn(db);
 const events:any={emitOrderUpdated:vi.fn()};const service=new ItemAvailabilityService(db,{authenticate:async()=>({id:'u',role})}as any,events);return{service,db,order,item,events};
}
describe('Atendimento de itens indisponíveis',()=>{
 it('aloca desconto em centavos sem ultrapassar o valor dos itens',()=>{const items=[{total:10.1},{total:5.5}];allocateCredit(items,12.6);expect(items).toEqual([{total:10.1,storeCreditShare:10.1},{total:5.5,storeCreditShare:2.5}]);});
 it('devolve apenas pagamento em dinheiro e restaura o voucher usado',()=>{expect(settlementAmounts({total:20,storeCreditShare:5},{deliveryFee:5.5},[{availabilityStatus:'AVAILABLE'}])).toEqual({cash:15,credit:5,voucher:20});});
 it('devolve também entrega quando o último item é removido',()=>{expect(settlementAmounts({total:20,storeCreditShare:5},{deliveryFee:5.5},[{availabilityStatus:'REFUNDED'}])).toEqual({cash:20.5,credit:5,voucher:25.5});});
 it('cria voucher uma única vez e cancela pedido sem itens entregáveis',async()=>{const f=fixture();await f.service.choose('o','i',{choice:'VOUCHER'});await f.service.choose('o','i',{choice:'VOUCHER'});expect(f.db.customerCreditEntry.upsert).toHaveBeenCalledTimes(1);expect(f.item.creditAmount).toBe(25.5);expect(f.order.status).toBe('CANCELED');expect(f.order.fulfillmentHold).toBe(false);});
 it('rejeita decisão de outra conta',async()=>{const f=fixture();f.order.customerId='other';await expect(f.service.choose('o','i',{choice:'VOUCHER'})).rejects.toThrow('pertence');expect(f.db.customerCreditEntry.upsert).not.toHaveBeenCalled();});
 it('rejeita substituição não oferecida',async()=>{const f=fixture();await expect(f.service.choose('o','i',{choice:'REPLACEMENT',productId:'unknown'})).rejects.toThrow('oferecida');});
 it('confirma alternativa com o mesmo preço e mantém valor pago',async()=>{const f=fixture();await f.service.choose('o','i',{choice:'REPLACEMENT',productId:'q'});expect(f.item).toMatchObject({productId:'q',productName:'Outro gin',availabilityStatus:'REPLACED'});expect(f.order.total).toBe(20.5);});
 it('revalida o preço da alternativa',async()=>{const f=fixture();f.db.product.findFirst.mockResolvedValue({id:'q',price:21});await expect(f.service.choose('o','i',{choice:'REPLACEMENT',productId:'q'})).rejects.toThrow('indisponível');});
 it('não permite marcar depois de atribuir motoboy',async()=>{const f=fixture('ADMIN');f.order.courierId='courier';await expect(f.service.mark('o','i',{unavailable:true})).rejects.toThrow('antes do despacho');});
 it('pausa despacho e permite restaurar antes da escolha',async()=>{const f=fixture('ADMIN');f.item.availabilityStatus='AVAILABLE';await f.service.mark('o','i',{unavailable:true});expect(f.order.fulfillmentHold).toBe(true);await f.service.mark('o','i',{unavailable:false});expect(f.order.fulfillmentHold).toBe(false);});
 it('aguarda Stripe antes de confirmar devolução e usa chave idempotente',async()=>{const f=fixture();const stripe=vi.spyOn(f.service as any,'stripe').mockResolvedValue({id:'re_test',payment_intent:'pi_test',currency:'brl',amount:2050,status:'pending'});await f.service.choose('o','i',{choice:'REFUND'});expect(stripe.mock.calls[0][2]).toBe('porto-prime:item:unique:refund:0');expect(f.item.availabilityStatus).toBe('REFUND_PROCESSING');expect(f.order.fulfillmentHold).toBe(true);expect(f.order.refundedTotal).toBe(0);stripe.mockResolvedValue({id:'re_test',payment_intent:'pi_test',currency:'brl',amount:2050,status:'succeeded'});await (f.service as any).processRefund('i');await (f.service as any).processRefund('i');expect(f.item.availabilityStatus).toBe('REFUNDED');expect(f.order.refundedTotal).toBe(20.5);expect(f.db.customerCreditEntry.upsert).toHaveBeenCalledTimes(1);expect(f.order.paymentStatus).toBe('REFUNDED');});
 it('retorno Stripe divergente não confirma reembolso',async()=>{const f=fixture();vi.spyOn(f.service as any,'stripe').mockResolvedValue({id:'re_test',payment_intent:'other',currency:'brl',amount:2050,status:'succeeded'});await expect(f.service.choose('o','i',{choice:'REFUND'})).rejects.toThrow('conferido');expect(f.order.refundedTotal).toBe(0);expect(f.item.availabilityStatus).toBe('REFUND_PROCESSING');});
});
