import {describe,it,expect} from 'vitest';
import {orderAdjustments} from './order-adjustments.js';
describe('Resumo consistente após remoção de produtos',()=>{
 it.each(['REFUND_PROCESSING','REFUNDED','VOUCHERED'])('subtrai item %s e preserva captura original',status=>{const original={total:155.5,deliveryFee:5.5,items:[{id:'removed',total:100,availabilityStatus:status,quantity:1},{id:'remaining',total:50,quantity:1,availabilityStatus:'AVAILABLE'}]};const result=orderAdjustments(original);expect(result).toMatchObject({total:155.5,removedItemsTotal:100,fulfillmentSubtotal:50,fulfillmentDeliveryFee:5.5,adjustedTotal:55.5});expect(result.fulfillmentItems.map(i=>i.id)).toEqual(['remaining']);expect(result.removedItems.map(i=>i.id)).toEqual(['removed']);expect(original.items).toHaveLength(2);});
 it('desconta somente voucher alocado em produtos que serão entregues',()=>{const result=orderAdjustments({total:55.5,deliveryFee:5.5,items:[{total:100,storeCreditShare:100,availabilityStatus:'REFUNDED'},{total:50,storeCreditShare:0,availabilityStatus:'AVAILABLE'}]});expect(result.adjustedTotal).toBe(55.5);expect(result.fulfillmentCreditUsed).toBe(0);});
 it('evita descontar crédito restaurado duas vezes',()=>{const result=orderAdjustments({total:55.5,deliveryFee:5.5,items:[{total:50,storeCreditShare:0,availabilityStatus:'VOUCHERED'},{total:100,storeCreditShare:100,availabilityStatus:'AVAILABLE'}]});expect(result.adjustedTotal).toBe(5.5);expect(result.fulfillmentCreditUsed).toBe(100);});
 it('cancela valor operacional e entrega quando não restam produtos',()=>{const result=orderAdjustments({total:105.5,deliveryFee:5.5,items:[{total:100,availabilityStatus:'REFUND_PROCESSING'}]});expect(result.adjustedTotal).toBe(0);expect(result.fulfillmentDeliveryFee).toBe(0);expect(result.total).toBe(105.5);});
 it('mantém item aguardando escolha e substituição confirmada na lista operacional',()=>{const result=orderAdjustments({deliveryFee:5.5,items:[{total:10,availabilityStatus:'AWAITING_CUSTOMER'},{total:20,availabilityStatus:'REPLACED'}]});expect(result.fulfillmentItems).toHaveLength(2);expect(result.adjustedTotal).toBe(35.5);});
});
