import 'package:flutter/material.dart';
import '../../../../core/navigation/app_nav.dart';
import '../../../../core/state/app_state.dart';
import '../../../../core/theme/app_theme.dart';
import '../../../checkout/presentation/pages/stripe_checkout_page.dart';
import '../../../orders/presentation/pages/order_tracking_page.dart';

class CartPage extends StatelessWidget{const CartPage({super.key});@override Widget build(BuildContext context)=>AnimatedBuilder(animation:AppState.instance,builder:(_,__){final s=AppState.instance,entries=s.cart.entries.toList();return SafeArea(bottom:false,child:ListView(padding:const EdgeInsets.fromLTRB(20,22,20,125),children:[
 Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Sua sacola',style:Theme.of(context).textTheme.headlineLarge),const SizedBox(height:4),Text(entries.isEmpty?'Pronta para o próximo brinde.':s.cartCount.toString()+' item(ns) selecionado(s)',style:const TextStyle(color:AppColors.muted,fontSize:11,fontWeight:FontWeight.w600))])),if(entries.isNotEmpty)TextButton(onPressed:s.clearCart,child:const Text('Limpar'))]),
 const SizedBox(height:18),
 if(entries.isEmpty)_Empty()else ...[
  ...entries.map((e)=>_Item(id:e.key,qty:e.value)),
  const SizedBox(height:8),_Summary(total:s.cartSubtotal),
  const SizedBox(height:12),Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(20)),child:const Row(children:[Icon(Icons.lock_rounded,color:AppColors.oceanDeep,size:20),SizedBox(width:10),Expanded(child:Text('Pagamento protegido pelo Stripe. Seus dados de cartão não passam pela Porto Prime.',style:TextStyle(fontSize:10,height:1.35,color:AppColors.oceanDeep,fontWeight:FontWeight.w700)))])),
  const SizedBox(height:14),SizedBox(height:58,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:AppColors.oceanDeep,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(19))),onPressed:s.loading?null:()=>_checkout(context),child:s.loading?const SizedBox(width:22,height:22,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Row(mainAxisAlignment:MainAxisAlignment.center,children:[Text('Continuar para checkout',style:TextStyle(fontWeight:FontWeight.w900)),SizedBox(width:8),Icon(Icons.arrow_forward_rounded,size:19)]))),
 ] ]));});}

class _Empty extends StatelessWidget{const _Empty();@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.fromLTRB(24,55,24,40),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(28),border:Border.all(color:const Color(0xFFE8ECE8))),child:Column(children:[Container(width:86,height:86,decoration:BoxDecoration(color:AppColors.sand,borderRadius:BorderRadius.circular(28)),child:const Icon(Icons.shopping_bag_outlined,size:42)),const SizedBox(height:18),const Text('Sua sacola está leve',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:6),const Text('Descubra bebidas, combos e tudo para o seu momento.',textAlign:TextAlign.center,style:TextStyle(color:AppColors.muted,fontSize:11,height:1.4)),const SizedBox(height:18),FilledButton(onPressed:()=>AppNav.instance.go(1),style:FilledButton.styleFrom(backgroundColor:AppColors.oceanDeep,padding:const EdgeInsets.symmetric(horizontal:22,vertical:14)),child:const Text('Explorar catálogo',style:TextStyle(fontWeight:FontWeight.w900))) ]));}

class _Item extends StatelessWidget{const _Item({required this.id,required this.qty});final String id;final int qty;@override Widget build(BuildContext context){final s=AppState.instance,p=s.product(id);if(p==null)return const SizedBox();final price=double.tryParse(p['price'].toString())??0;return Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),border:Border.all(color:const Color(0xFFE8ECE8))),child:Row(children:[Container(width:68,height:68,clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(18)),child:p['imageUrl']!=null?Image.network(p['imageUrl'],fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.local_drink_rounded)):const Icon(Icons.local_drink_rounded)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p['name']??'',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:13,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text('R\$ '+price.toStringAsFixed(2).replaceAll('.',','),style:const TextStyle(color:AppColors.oceanDeep,fontSize:12,fontWeight:FontWeight.w900))])),Container(decoration:BoxDecoration(color:AppColors.canvas,borderRadius:BorderRadius.circular(14)),child:Row(children:[_q(Icons.remove_rounded,()=>s.changeQty(id,-1)),Text(qty.toString(),style:const TextStyle(fontSize:12,fontWeight:FontWeight.w900)),_q(Icons.add_rounded,()=>s.changeQty(id,1))]))]));}Widget _q(IconData i,VoidCallback tap)=>InkWell(onTap:tap,child:Padding(padding:const EdgeInsets.all(9),child:Icon(i,size:16)));}

class _Summary extends StatelessWidget{const _Summary({required this.total});final double total;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(23),border:Border.all(color:const Color(0xFFE8ECE8))),child:Column(children:[_row('Subtotal','R\$ '+total.toStringAsFixed(2).replaceAll('.',',')),const SizedBox(height:10),_row('Entrega','Calculada no pedido',muted:true),const Padding(padding:EdgeInsets.symmetric(vertical:13),child:Divider(height:1)),_row('Total','R\$ '+total.toStringAsFixed(2).replaceAll('.',','),strong:true)]));Widget _row(String a,String b,{bool muted=false,bool strong=false})=>Row(children:[Expanded(child:Text(a,style:TextStyle(fontSize:strong?15:11,fontWeight:strong?FontWeight.w900:FontWeight.w700,color:muted?AppColors.muted:AppColors.ink))),Text(b,style:TextStyle(fontSize:strong?18:11,fontWeight:strong?FontWeight.w900:FontWeight.w700,color:muted?AppColors.muted:AppColors.ink))]);}

Future<void> _checkout(BuildContext context)async{
 final s=AppState.instance;
 if(!s.loggedIn||!s.isCustomer){AppNav.instance.go(3);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Entre ou crie sua conta de cliente para continuar.')));return;}
 if(s.addresses.isEmpty){AppNav.instance.go(3);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Cadastre um endereço de entrega no Perfil.')));return;}
 String selected=s.addresses.firstWhere((a)=>a['isDefault']==true,orElse:()=>s.addresses.first)['id'].toString();
 final ok=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,backgroundColor:Colors.transparent,builder:(c)=>StatefulBuilder(builder:(c,set)=>Material(color:Colors.white,borderRadius:const BorderRadius.vertical(top:Radius.circular(32)),clipBehavior:Clip.antiAlias,child:Padding(padding:const EdgeInsets.fromLTRB(20,12,20,24),child:SafeArea(top:false,child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[
  Center(child:Container(width:42,height:4,decoration:BoxDecoration(color:const Color(0xFFD8DDDA),borderRadius:BorderRadius.circular(10)))),const SizedBox(height:18),const Text('Confirmar entrega',style:TextStyle(fontSize:23,fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text('Escolha onde receber seu pedido.',style:TextStyle(color:AppColors.muted,fontSize:11)),const SizedBox(height:14),
  ...s.addresses.map((a)=>RadioListTile<String>(value:a['id'].toString(),groupValue:selected,onChanged:(v)=>set(()=>selected=v!),contentPadding:EdgeInsets.zero,activeColor:AppColors.oceanDeep,title:Text((a['street']??'')+', '+(a['number']??''),style:const TextStyle(fontWeight:FontWeight.w800,fontSize:13)),subtitle:Text((a['neighborhood']??'')+' • Porto Seguro',style:const TextStyle(fontSize:10)))),
  const SizedBox(height:8),Container(padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(17)),child:const Row(children:[Icon(Icons.lock_rounded,color:AppColors.oceanDeep,size:19),SizedBox(width:9),Expanded(child:Text('Pagamento seguro dentro do app. Após a confirmação você vai direto para o acompanhamento do pedido.',style:TextStyle(fontSize:9,height:1.35,color:AppColors.oceanDeep,fontWeight:FontWeight.w700)))])),const SizedBox(height:10),SizedBox(width:double.infinity,height:54,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:AppColors.oceanDeep),onPressed:()=>Navigator.pop(c,true),child:const Text('Continuar para pagamento',style:TextStyle(fontWeight:FontWeight.w900)))),
 ]))))));
 if(ok!=true)return;
 try{final order=await s.createOrder(selected);if(!context.mounted)return;final orderId=order['id'].toString();final payment=await s.createCheckout(orderId);if(!context.mounted)return;final paid=await Navigator.of(context).push<bool>(MaterialPageRoute(fullscreenDialog:true,builder:(_)=>StripeCheckoutPage(clientSecret:payment['clientSecret'].toString(),publishableKey:payment['publishableKey'].toString(),orderId:orderId)));if(!context.mounted)return;if(paid==true){s.clearCart();await Future.wait([s.loadOrders(),s.loadActiveOrder()]);if(!context.mounted)return;final track=await _paymentApproved(context,orderId);if(!context.mounted)return;if(track==true){await Navigator.of(context).push(MaterialPageRoute(builder:(_)=>OrderTrackingPage(orderId:orderId)));}}else{ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Pedido criado. Você pode concluir o pagamento depois.')));}}catch(e){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}
}


Future<bool?> _paymentApproved(BuildContext context,String orderId){
 final s=AppState.instance;dynamic order;for(final o in s.orders){if(o['id'].toString()==orderId){order=o;break;}}final total=double.tryParse((order?['total']??0).toString())??0;
 Future.delayed(const Duration(seconds:5),(){if(context.mounted&&Navigator.of(context).canPop())Navigator.of(context).pop(true);});
 return showModalBottomSheet<bool>(
 context:context,isScrollControlled:true,isDismissible:false,enableDrag:false,backgroundColor:Colors.transparent,
 builder:(c)=>Material(color:Colors.transparent,child:Container(padding:const EdgeInsets.fromLTRB(22,14,22,26),decoration:const BoxDecoration(color:Colors.white,borderRadius:BorderRadius.vertical(top:Radius.circular(36))),child:SafeArea(top:false,child:Column(mainAxisSize:MainAxisSize.min,children:[
  Container(width:42,height:4,decoration:BoxDecoration(color:const Color(0xFFDDE3DF),borderRadius:BorderRadius.circular(20))),const SizedBox(height:25),
  Stack(alignment:Alignment.center,children:[Container(width:104,height:104,decoration:BoxDecoration(color:AppColors.mint,shape:BoxShape.circle,boxShadow:[BoxShadow(color:AppColors.oceanDeep.withValues(alpha:.14),blurRadius:32,spreadRadius:5)])),Container(width:72,height:72,decoration:const BoxDecoration(color:AppColors.oceanDeep,shape:BoxShape.circle),child:const Icon(Icons.check_rounded,color:Colors.white,size:42))]),
  const SizedBox(height:22),const Text('Pagamento aprovado!',textAlign:TextAlign.center,style:TextStyle(fontSize:28,fontWeight:FontWeight.w900,letterSpacing:-.9)),const SizedBox(height:8),
  const Text('Seu pedido já está com a Porto Prime.',textAlign:TextAlign.center,style:TextStyle(fontSize:12,color:AppColors.muted,fontWeight:FontWeight.w700)),const SizedBox(height:22),
  Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF102D28),Color(0xFF08786D)]),borderRadius:BorderRadius.circular(22)),child:const Row(children:[Icon(Icons.storefront_rounded,color:Color(0xFF8CFFE4),size:25),SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Aguardando a distribuidora',style:TextStyle(color:Colors.white,fontSize:13,fontWeight:FontWeight.w900)),SizedBox(height:3),Text('Estamos aguardando a confirmação e liberação dos itens. Depois, conectamos um motoboy.',style:TextStyle(color:Color(0xFFD4ECE7),fontSize:9.5,height:1.4,fontWeight:FontWeight.w600))]))])),
  const SizedBox(height:14),Row(children:[_approvedMini(Icons.credit_card_rounded,'VALOR PAGO','R\$ '+total.toStringAsFixed(2).replaceAll('.',',')),const SizedBox(width:9),_approvedMini(Icons.receipt_long_rounded,'PEDIDO','#'+orderId.substring(0,8).toUpperCase())]),const SizedBox(height:18),
  SizedBox(width:double.infinity,height:58,child:FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:AppColors.oceanDeep,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(19))),onPressed:()=>Navigator.pop(c,true),icon:const Icon(Icons.route_rounded),label:const Text('Acompanhar meu pedido',style:TextStyle(fontWeight:FontWeight.w900,fontSize:13)))),
  const SizedBox(height:8),TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Continuar comprando',style:TextStyle(color:AppColors.muted,fontWeight:FontWeight.w800)))
 ])))));
}
Widget _approvedMini(IconData icon,String a,String b)=>Expanded(child:Container(padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:AppColors.canvas,borderRadius:BorderRadius.circular(18),border:Border.all(color:const Color(0xFFE7ECE8))),child:Row(children:[Icon(icon,color:AppColors.oceanDeep,size:20),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:7.5,color:AppColors.muted,fontWeight:FontWeight.w900,letterSpacing:.7)),Text(b,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:10,fontWeight:FontWeight.w900))]))])));
