import 'package:flutter/material.dart';
import '../../../../core/theme/app_theme.dart';
import '../../../../core/state/app_state.dart';
class CartPage extends StatelessWidget{const CartPage({super.key});@override Widget build(BuildContext context)=>AnimatedBuilder(animation:AppState.instance,builder:(_,__) {final s=AppState.instance;final entries=s.cart.entries.toList();double total=0;for(final e in entries){final p=s.product(e.key);if(p!=null)total+=(double.tryParse(p['price'].toString())??0)*e.value;}return SafeArea(bottom:false,child:ListView(padding:const EdgeInsets.fromLTRB(20,22,20,120),children:[
 Row(children:[Expanded(child:Text('Sua sacola',style:Theme.of(context).textTheme.headlineLarge)),Text(s.cartCount.toString()+' itens',style:const TextStyle(fontWeight:FontWeight.w900,color:AppColors.oceanDeep))]),const SizedBox(height:18),
 if(entries.isEmpty)Container(padding:const EdgeInsets.symmetric(vertical:70),child:const Column(children:[Icon(Icons.shopping_bag_outlined,size:64,color:AppColors.ocean),SizedBox(height:14),Text('Sua sacola está vazia',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),SizedBox(height:5),Text('Adicione produtos na Home.',style:TextStyle(color:AppColors.muted))]))
 else ...[for(final e in entries)_Item(id:e.key,qty:e.value),const SizedBox(height:12),Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22)),child:Row(children:[const Expanded(child:Text('Total',style:TextStyle(fontWeight:FontWeight.w900))),Text('R\$ '+total.toStringAsFixed(2).replaceAll('.',','),style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900))])),const SizedBox(height:12),SizedBox(height:56,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:AppColors.oceanDeep),onPressed:()=>_finish(context),child:const Text('Finalizar pedido',style:TextStyle(fontWeight:FontWeight.w900))))],
]));});}
class _Item extends StatelessWidget{const _Item({required this.id,required this.qty});final String id;final int qty;@override Widget build(BuildContext context){final s=AppState.instance,p=s.product(id);if(p==null)return const SizedBox();return Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22)),child:Row(children:[Container(width:65,height:65,decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(17)),child:const Icon(Icons.local_drink_rounded)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p['name']??'',style:const TextStyle(fontWeight:FontWeight.w900)),Text('R\$ '+p['price'].toString(),style:const TextStyle(color:AppColors.muted,fontSize:11))])),IconButton(onPressed:()=>s.changeQty(id,-1),icon:const Icon(Icons.remove_circle_outline)),Text('$qty',style:const TextStyle(fontWeight:FontWeight.w900)),IconButton(onPressed:()=>s.changeQty(id,1),icon:const Icon(Icons.add_circle,color:AppColors.ocean))]));}}
Future<void> _finish(BuildContext context)async{final s=AppState.instance;if(!s.loggedIn||!s.isCustomer){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Entre como cliente no Perfil para finalizar.')));return;}if(s.addresses.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Cadastre um endereço no Perfil antes de finalizar.')));return;}final a=await showModalBottomSheet<String>(context:context,builder:(c)=>SafeArea(child:Padding(padding:const EdgeInsets.all(18),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Entregar em',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:10),...s.addresses.map((x)=>ListTile(onTap:()=>Navigator.pop(c,x['id']),leading:const Icon(Icons.location_on_rounded),title:Text((x['street']??'')+', '+(x['number']??'')),subtitle:Text(x['neighborhood']??'')))]))));if(a==null)return;try{await s.checkout(a);if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Pedido criado com sucesso!')));}catch(e){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}
