import 'package:flutter/material.dart';
import '../../../../core/state/app_state.dart'; import '../../../../core/theme/app_theme.dart';
class AuthPage extends StatefulWidget{const AuthPage({super.key});@override State<AuthPage> createState()=>_AuthPageState();}
class _AuthPageState extends State<AuthPage>{
 bool register=false,busy=false,statusMode=false;String role='CUSTOMER';String? error;Map<String,dynamic>? status;
 final name=TextEditingController(),email=TextEditingController(),password=TextEditingController(),phone=TextEditingController(),business=TextEditingController(),document=TextEditingController(),cnh=TextEditingController(),plate=TextEditingController(),year=TextEditingController();String model='Honda CG 160';String brand='Honda';
 final models=['Honda CG 160','Honda Biz 125','Honda Pop 110i','Honda XRE 190','Yamaha Factor 150','Yamaha Fazer FZ15','Yamaha Crosser 150','Yamaha NMAX 160','Shineray Jet 125','Outra'];
 Future<void> check()async{setState(()=>{busy=true,error=null,status=null});try{status=await AppState.instance.courierStatus(document.text);}catch(e){error=e.toString();}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> submit()async{setState(()=>{busy=true,error=null});try{if(register){await AppState.instance.register(name:name.text,email:email.text,password:password.text,phone:phone.text,role:role,businessName:business.text,document:document.text,cnh:cnh.text,cnhCategory:'A',vehicleBrand:brand,vehicleModel:model,vehiclePlate:plate.text,vehicleYear:int.tryParse(year.text));if(role!='CUSTOMER'&&mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Candidatura enviada para análise.')));setState(()=>statusMode=role=='COURIER');return;}}else{await AppState.instance.login(email.text,password.text);}if(mounted)Navigator.pop(context);}catch(e){setState(()=>error=e.toString());}finally{if(mounted)setState(()=>busy=false);}}
 Widget field(TextEditingController c,String label,IconData icon,{TextInputType? type})=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextField(controller:c,keyboardType:type,decoration:InputDecoration(labelText:label,prefixIcon:Icon(icon))));
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:AppColors.canvas,appBar:AppBar(backgroundColor:Colors.transparent,title:Text(statusMode?'Acompanhar candidatura':register?'Criar sua conta':'Entrar')),body:ListView(padding:const EdgeInsets.all(22),children:[
  Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(colors:[AppColors.primaryDark,AppColors.primary]),borderRadius:BorderRadius.circular(30)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('PORTO PRIME',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,letterSpacing:1)),const SizedBox(height:8),Text(statusMode?'Já se candidatou?\nConsulte pelo CPF.':register?'Faça parte da operação\nque move Porto Seguro.':'Bem-vindo de volta.',style:const TextStyle(color:Colors.white,fontSize:24,fontWeight:FontWeight.w900,height:1.1))])),
  const SizedBox(height:20),
  if(statusMode)...[field(document,'CPF da candidatura',Icons.badge_outlined,type:TextInputType.number),FilledButton.icon(onPressed:busy?null:check,icon:const Icon(Icons.search),label:const Text('VERIFICAR STATUS')),if(status!=null)...[const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(status!['name']?.toString()??'',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),Text(status!['document']?.toString()??''),const SizedBox(height:10),Text('Status: ${status!['approvalStatus']}',style:const TextStyle(fontWeight:FontWeight.w800)),if(status!['hasPendingRequirements']==true)const Padding(padding:EdgeInsets.only(top:8),child:Text('Há pendências solicitadas pelo administrador. Entre na sua conta para responder.',style:TextStyle(color:Colors.deepOrange,fontWeight:FontWeight.w700)))])))],TextButton(onPressed:()=>setState(()=>{statusMode=false,register=false,status=null,error=null}),child:const Text('Entrar para responder pendências'))]
  else ...[
   if(register)...[field(name,'Nome completo',Icons.person_outline),field(phone,'Telefone',Icons.phone_outlined,type:TextInputType.phone),const Text('Como você vai usar a Porto Prime?',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:8),Wrap(spacing:8,children:[for(final r in const [('CUSTOMER','Cliente'),('COURIER','Motoboy'),('PARTNER','Parceiro')])ChoiceChip(label:Text(r.$2),selected:role==r.$1,onSelected:(_)=>setState(()=>role=r.$1))]),const SizedBox(height:14),
    if(role=='PARTNER')field(business,'Nome do estabelecimento',Icons.storefront_outlined),
    if(role=='COURIER')...[field(document,'CPF',Icons.badge_outlined,type:TextInputType.number),field(cnh,'Número da CNH',Icons.credit_card_outlined),DropdownButtonFormField<String>(initialValue:model,items:models.map((m)=>DropdownMenuItem(value:m,child:Text(m))).toList(),onChanged:(v)=>setState(()=>model=v!),decoration:const InputDecoration(labelText:'Modelo da moto',prefixIcon:Icon(Icons.two_wheeler))),const SizedBox(height:12),field(plate,'Placa da moto',Icons.pin_outlined),field(year,'Ano da moto',Icons.calendar_month_outlined,type:TextInputType.number)],
    if(role=='PARTNER')field(document,'CPF/CNPJ',Icons.badge_outlined)],
   field(email,'E-mail',Icons.mail_outline_rounded,type:TextInputType.emailAddress),field(password,'Senha (mínimo 8 caracteres)',Icons.lock_outline_rounded),
   FilledButton(onPressed:busy?null:submit,style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(56)),child:busy?const CircularProgressIndicator():Text(register?'ENVIAR CADASTRO':'ENTRAR',style:const TextStyle(fontWeight:FontWeight.w900))),
   TextButton(onPressed:busy?null:()=>setState(()=>register=!register),child:Text(register?'Já tenho conta • Entrar':'Ainda não tenho conta • Cadastrar')),
   if(!register)OutlinedButton.icon(onPressed:()=>setState(()=>{statusMode=true,error=null}),icon:const Icon(Icons.fact_check_outlined),label:const Text('JÁ ME CANDIDATEI • VER STATUS'))
  ],
  if(error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(error!,style:const TextStyle(color:Colors.red,fontWeight:FontWeight.w700)))
 ]));}
}