import 'package:flutter/foundation.dart';
import '../api/api_client.dart'; import '../models/models.dart';
class AppState extends ChangeNotifier{
 AppState._();static final instance=AppState._();final api=ApiClient();AppUser? user;List<CategoryModel> categories=[];List<ProductModel> products=[];List<AddressModel> addresses=[];final List<CartLine> cart=[];bool loading=false;String? error;
 int get cartCount=>cart.fold(0,(n,e)=>n+e.quantity);double get cartTotal=>cart.fold(0,(n,e)=>n+e.total);
 Future<void> bootstrap()async{loading=true;notifyListeners();try{final r=await Future.wait([api.get('/categories'),api.get('/products')]);categories=(r[0] as List).map((e)=>CategoryModel.fromJson(Map<String,dynamic>.from(e))).toList();products=(r[1] as List).map((e)=>ProductModel.fromJson(Map<String,dynamic>.from(e))).toList();}catch(e){error=e.toString();}loading=false;notifyListeners();}
 void add(ProductModel p){final i=cart.indexWhere((e)=>e.product.id==p.id);if(i<0)cart.add(CartLine(product:p));else cart[i].quantity++;notifyListeners();}
 void changeQty(ProductModel p,int d){final i=cart.indexWhere((e)=>e.product.id==p.id);if(i<0)return;cart[i].quantity+=d;if(cart[i].quantity<=0)cart.removeAt(i);notifyListeners();}
 Future<void> login(String e,String p)async{final d=Map<String,dynamic>.from(await api.post('/auth/login',body:{'email':e,'password':p}));api.token=d['token']?.toString();user=AppUser.fromJson(Map<String,dynamic>.from(d['user']));notifyListeners();}
 Future<void> register({required String name,required String email,required String password,required String role,String? phone,String? businessName,String? document,String? cnh,String? cnhCategory,String? vehicleBrand,String? vehicleModel,String? vehiclePlate,int? vehicleYear})async{await api.post('/auth/register',body:{'name':name,'email':email,'password':password,'role':role,'phone':phone,'businessName':businessName,'document':document,'cnh':cnh,'cnhCategory':cnhCategory,'vehicleBrand':vehicleBrand,'vehicleModel':vehicleModel,'vehiclePlate':vehiclePlate,'vehicleYear':vehicleYear});if(role=='CUSTOMER')await login(email,password);}
 Future<Map<String,dynamic>> courierStatus(String cpf)async=>Map<String,dynamic>.from(await api.post('/couriers/application/status',body:{'document':cpf}));
 Future<Map<String,dynamic>> courierApplication()async=>Map<String,dynamic>.from(await api.get('/couriers/application/me',authenticated:true));
 Future<void> respondRequirement(String id,String response)async{await api.post('/couriers/requirements/$id/respond',authenticated:true,body:{'response':response});}
 Future<void> loadAddresses()async{if(user==null)return;final r=await api.get('/addresses',authenticated:true);addresses=(r as List).map((e)=>AddressModel.fromJson(Map<String,dynamic>.from(e))).toList();notifyListeners();}
 Future<AddressModel> createAddress({required String street,required String number,required String neighborhood,required String postalCode,String? complement})async{final d=Map<String,dynamic>.from(await api.post('/addresses',authenticated:true,body:{'label':'Casa','street':street,'number':number,'complement':complement,'neighborhood':neighborhood,'city':'Porto Seguro','state':'BA','postalCode':postalCode,'isDefault':true}));final a=AddressModel.fromJson(d);addresses.add(a);notifyListeners();return a;}
 Future<dynamic> createOrder(String addressId)async{if(cart.isEmpty)throw ApiException('Seu carrinho está vazio.');final r=await api.post('/orders',authenticated:true,body:{'addressId':addressId,'items':cart.map((e)=>{'productId':e.product.id,'quantity':e.quantity}).toList()});cart.clear();notifyListeners();return r;}
 Future<void> logout()async{try{await api.post('/auth/logout',authenticated:true);}catch(_){}api.token=null;user=null;addresses=[];notifyListeners();}
}