import 'package:flutter/material.dart';
import '../../../../core/state/app_state.dart';
import '../../../../core/theme/app_theme.dart';

class CategoriesPage extends StatefulWidget{const CategoriesPage({super.key});@override State<CategoriesPage> createState()=>_CategoriesPageState();}
class _CategoriesPageState extends State<CategoriesPage>{
 final search=TextEditingController();String selected='Todos';
 static const featured=['Cervejas','Refrigerantes','Whiskies','Gins','Vodkas','Vinhos','Energéticos','Águas e Gelo','Conveniência'];
 static const icons=<String,IconData>{'Cervejas':Icons.sports_bar_rounded,'Refrigerantes':Icons.local_drink_rounded,'Whiskies':Icons.liquor_rounded,'Gins':Icons.local_bar_rounded,'Vodkas':Icons.liquor_rounded,'Vinhos':Icons.wine_bar_rounded,'Energéticos':Icons.bolt_rounded,'Águas e Gelo':Icons.ac_unit_rounded,'Conveniência':Icons.shopping_basket_rounded};
 @override void dispose(){search.dispose();super.dispose();}
 @override Widget build(BuildContext context)=>AnimatedBuilder(animation:AppState.instance,builder:(_,__){final s=AppState.instance;final found=s.products.map((p)=>(p['category']?['name']??'Outros').toString()).toSet();final names=<String>['Todos',...featured.where(found.contains),...found.where((x)=>!featured.contains(x))];final q=search.text.toLowerCase().trim();final list=s.products.where((p){final cat=(p['category']?['name']??'Outros').toString();return(selected=='Todos'||cat==selected)&&(q.isEmpty||(p['name']??'').toString().toLowerCase().contains(q)||cat.toLowerCase().contains(q));}).toList();
 return SafeArea(bottom:false,child:CustomScrollView(physics:const BouncingScrollPhysics(),slivers:[
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,22,20,0),sliver:SliverToBoxAdapter(child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Descobrir',style:Theme.of(context).textTheme.headlineLarge),const SizedBox(height:5),const Text('Encontre o que combina com agora.',style:TextStyle(color:AppColors.muted,fontWeight:FontWeight.w600))])),Container(width:45,height:45,decoration:BoxDecoration(color:AppColors.sand,borderRadius:BorderRadius.circular(16)),child:const Icon(Icons.auto_awesome_rounded))]))),
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,18,20,12),sliver:SliverToBoxAdapter(child:TextField(controller:search,onChanged:(_)=>setState((){}),decoration:InputDecoration(hintText:'Buscar bebida ou categoria',prefixIcon:const Icon(Icons.search_rounded),suffixIcon:q.isEmpty?null:IconButton(onPressed:(){search.clear();setState((){});},icon:const Icon(Icons.close_rounded)),filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(19),borderSide:BorderSide.none),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(19),borderSide:const BorderSide(color:Color(0xFFE7EBE7))))))),
 SliverToBoxAdapter(child:SizedBox(height:104,child:ListView.separated(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:20),itemCount:names.length,separatorBuilder:(_,__)=>const SizedBox(width:10),itemBuilder:(_,i){final n=names[i],on=n==selected;final icon=n=='Todos'?Icons.grid_view_rounded:(icons[n]??Icons.local_drink_rounded);return InkWell(onTap:()=>setState(()=>selected=n),borderRadius:BorderRadius.circular(22),child:AnimatedContainer(duration:const Duration(milliseconds:180),width:94,padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:on?AppColors.oceanDeep:Colors.white,borderRadius:BorderRadius.circular(22),border:Border.all(color:on?AppColors.oceanDeep:const Color(0xFFE7EBE7)),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.035),blurRadius:14,offset:const Offset(0,5))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:38,height:38,decoration:BoxDecoration(color:on?Colors.white.withValues(alpha:.15):AppColors.mint,borderRadius:BorderRadius.circular(13)),child:Icon(icon,size:21,color:on?Colors.white:AppColors.oceanDeep)),const Spacer(),Text(n,maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(color:on?Colors.white:AppColors.ink,fontWeight:FontWeight.w900,fontSize:10))])));}))),
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,22,20,10),sliver:SliverToBoxAdapter(child:Row(children:[Expanded(child:Text(selected=='Todos'?'Catálogo Porto Prime':selected,style:Theme.of(context).textTheme.titleLarge)),Text(list.length.toString()+' opções',style:const TextStyle(color:AppColors.muted,fontSize:11,fontWeight:FontWeight.w700))]))),
 if(list.isEmpty)SliverFillRemaining(hasScrollBody:false,child:Center(child:Padding(padding:const EdgeInsets.all(30),child:Column(mainAxisSize:MainAxisSize.min,children:[Container(width:68,height:68,decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(22)),child:const Icon(Icons.cloud_off_rounded,color:AppColors.oceanDeep,size:31)),const SizedBox(height:14),Text(s.error!=null?'Não foi possível carregar o catálogo.':'Nenhum produto encontrado.',textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:15)),const SizedBox(height:10),FilledButton(onPressed:()=>s.loadProducts(),child:const Text('Recarregar catálogo'))]))))else SliverPadding(padding:const EdgeInsets.fromLTRB(20,0,20,120),sliver:SliverGrid(delegate:SliverChildBuilderDelegate((_,i)=>_Product(p:list[i]),childCount:list.length),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:.72))),
 ]));});}

class _Product extends StatelessWidget{const _Product({required this.p});final dynamic p;@override Widget build(BuildContext context){final s=AppState.instance;final price=double.tryParse(p['price'].toString())??0;final id=p['id'].toString();final qty=s.cart[id]??0;return InkWell(onTap:()=>_details(context,p),borderRadius:BorderRadius.circular(24),child:Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24),border:Border.all(color:const Color(0xFFE8ECE8))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
 Expanded(child:Stack(children:[Container(width:double.infinity,decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(19)),alignment:Alignment.center,child:p['imageUrl']!=null?ClipRRect(borderRadius:BorderRadius.circular(19),child:Image.network(p['imageUrl'],fit:BoxFit.cover,width:double.infinity,height:double.infinity,errorBuilder:(_,__,___)=>const Icon(Icons.local_drink_rounded,size:50))):const Icon(Icons.local_drink_rounded,size:50)),if(qty>0)Positioned(top:8,right:8,child:Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:5),decoration:BoxDecoration(color:AppColors.coral,borderRadius:BorderRadius.circular(12)),child:Text(qty.toString()+' na sacola',style:const TextStyle(color:Colors.white,fontSize:8,fontWeight:FontWeight.w900))))])),
 const SizedBox(height:9),Text(p['name']??'',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:13,fontWeight:FontWeight.w900,height:1.15)),const SizedBox(height:3),Text(p['category']?['name']??'Porto Prime',style:const TextStyle(fontSize:9,color:AppColors.muted,fontWeight:FontWeight.w600)),const Spacer(),Row(children:[Expanded(child:Text('R\$ '+price.toStringAsFixed(2).replaceAll('.',','),style:const TextStyle(fontSize:14,fontWeight:FontWeight.w900))),InkWell(onTap:()=>s.addProduct(id),child:Container(width:35,height:35,decoration:BoxDecoration(color:AppColors.ink,borderRadius:BorderRadius.circular(12)),child:const Icon(Icons.add_rounded,color:Colors.white,size:20)))])
 ])));}}

void _details(BuildContext context,dynamic p){final price=double.tryParse(p['price'].toString())??0;showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:Colors.transparent,builder:(c)=>Container(padding:const EdgeInsets.fromLTRB(20,12,20,26),decoration:const BoxDecoration(color:Colors.white,borderRadius:BorderRadius.vertical(top:Radius.circular(32))),child:SafeArea(top:false,child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Center(child:Container(width:42,height:4,decoration:BoxDecoration(color:const Color(0xFFD9DEDA),borderRadius:BorderRadius.circular(10)))),const SizedBox(height:18),Container(height:180,width:double.infinity,decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(25)),alignment:Alignment.center,child:p['imageUrl']!=null?ClipRRect(borderRadius:BorderRadius.circular(25),child:Image.network(p['imageUrl'],fit:BoxFit.cover,width:double.infinity,height:180)):const Icon(Icons.local_drink_rounded,size:76)),const SizedBox(height:18),Text(p['name']??'',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900,letterSpacing:-.5)),const SizedBox(height:5),Text(p['description']??'Selecionado para chegar gelado e rápido até você.',style:const TextStyle(color:AppColors.muted,fontSize:12,height:1.4)),const SizedBox(height:18),Row(children:[Expanded(child:Text('R\$ '+price.toStringAsFixed(2).replaceAll('.',','),style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900))),FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:AppColors.oceanDeep,padding:const EdgeInsets.symmetric(horizontal:20,vertical:15)),onPressed:(){AppState.instance.addProduct(p['id']);Navigator.pop(c);},icon:const Icon(Icons.add_rounded),label:const Text('Adicionar',style:TextStyle(fontWeight:FontWeight.w900)))])]))));}
