import 'dart:async';
import 'package:flutter/material.dart';
import '../../../../core/navigation/app_nav.dart';
import '../../../../core/state/app_state.dart';
import '../../../../core/theme/app_theme.dart';

class OrderTrackingPage extends StatefulWidget{
 const OrderTrackingPage({super.key,required this.orderId});final String orderId;
 @override State<OrderTrackingPage> createState()=>_OrderTrackingPageState();
}
class _OrderTrackingPageState extends State<OrderTrackingPage>{
 Timer? timer;
 @override void initState(){super.initState();_refresh();timer=Timer.periodic(const Duration(seconds:4),(_)=>_refresh());}
 Future<void> _refresh()async{try{await Future.wait([AppState.instance.loadOrders(),AppState.instance.loadActiveOrder()]);}catch(_){}}
 @override void dispose(){timer?.cancel();super.dispose();}
 Map<String,dynamic>? get order{for(final x in AppState.instance.orders){final o=Map<String,dynamic>.from(x);if(o['id'].toString()==widget.orderId)return o;}final a=AppState.instance.activeOrder;return a?['id'].toString()==widget.orderId?a:null;}
 @override Widget build(BuildContext context)=>AnimatedBuilder(animation:AppState.instance,builder:(_,__){final o=order;if(o==null)return Scaffold(backgroundColor:AppColors.canvas,appBar:AppBar(backgroundColor:AppColors.canvas),body:const Center(child:CircularProgressIndicator()));final status=o['status'].toString(),step=_step(status),courier=o['courier'],items=(o['items'] as List?)??const [],address=o['address'];return Scaffold(backgroundColor:AppColors.canvas,
 appBar:AppBar(backgroundColor:AppColors.canvas,surfaceTintColor:AppColors.canvas,title:const Text('Detalhes do pedido',style:TextStyle(fontSize:16,fontWeight:FontWeight.w900)),actions:[IconButton(tooltip:'Início',onPressed:(){Navigator.of(context).popUntil((r)=>r.isFirst);AppNav.instance.go(0);},icon:const Icon(Icons.home_rounded))]),
 body:SafeArea(child:RefreshIndicator(onRefresh:_refresh,child:ListView(padding:const EdgeInsets.fromLTRB(20,8,20,34),children:[
 _Hero(order:o,status:status,id:widget.orderId),
 const SizedBox(height:16),_Journey(status:status,step:step),
 if(courier!=null)...[const SizedBox(height:16),_Courier(courier:courier)],
 const SizedBox(height:16),_Section(title:'Seu pedido',icon:Icons.shopping_bag_rounded,child:Column(children:[...items.map((x)=>Padding(padding:const EdgeInsets.only(bottom:11),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:34,height:34,alignment:Alignment.center,decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(11)),child:Text('${x['quantity']}x',style:const TextStyle(fontSize:10,fontWeight:FontWeight.w900,color:AppColors.oceanDeep))),const SizedBox(width:10),Expanded(child:Text(x['productName']?.toString()??'Produto',style:const TextStyle(fontSize:12,fontWeight:FontWeight.w800))),Text(_money(x['total']),style:const TextStyle(fontSize:11,fontWeight:FontWeight.w900))]))),const Divider(),_value('Subtotal',o['subtotal']),_value('Entrega',o['deliveryFee']),const SizedBox(height:7),_value('Total',o['total'],strong:true)])),
 if(address!=null)...[const SizedBox(height:16),_Section(title:'Entrega',icon:Icons.location_on_rounded,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${address['street']??''}, ${address['number']??''}',style:const TextStyle(fontSize:13,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text('${address['neighborhood']??''} • ${address['city']??''} - ${address['state']??''}',style:const TextStyle(fontSize:10,color:AppColors.muted,height:1.4)),if((address['complement']??'').toString().isNotEmpty)Text(address['complement'].toString(),style:const TextStyle(fontSize:10,color:AppColors.muted))]))],
 const SizedBox(height:16),_Section(title:'Pagamento e identificação',icon:Icons.verified_user_rounded,child:Column(children:[_info('Pedido','#${widget.orderId.substring(0,widget.orderId.length<8?widget.orderId.length:8).toUpperCase()}'),_info('Pagamento',o['paymentStatus']=='PAID'?'Aprovado':'${o['paymentStatus']}'),_info('Forma',o['paymentMethod']=='CARD'?'Cartão • Stripe':(o['paymentMethod']??'—').toString()),_info('Criado em',_date(o['createdAt'])),if(o['deliveredAt']!=null)_info('Entregue em',_date(o['deliveredAt']))])),
 const SizedBox(height:18),OutlinedButton.icon(onPressed:(){Navigator.of(context).popUntil((r)=>r.isFirst);AppNav.instance.go(0);},icon:const Icon(Icons.home_rounded),label:const Text('Voltar para o início',style:TextStyle(fontWeight:FontWeight.w900)),style:OutlinedButton.styleFrom(minimumSize:const Size.fromHeight(54),foregroundColor:AppColors.oceanDeep,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18)))),
 ]))));});
}
class _Hero extends StatelessWidget{const _Hero({required this.order,required this.status,required this.id});final dynamic order;final String status,id;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF102D28),Color(0xFF08786D)]),borderRadius:BorderRadius.circular(30),boxShadow:const [BoxShadow(color:Color(0x1C000000),blurRadius:28,offset:Offset(0,14))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:7),decoration:BoxDecoration(color:Colors.white12,borderRadius:BorderRadius.circular(12)),child:Row(children:[Icon(status=='DELIVERED'?Icons.check_circle_rounded:Icons.radio_button_checked_rounded,color:const Color(0xFF8CFFE4),size:12),const SizedBox(width:5),Text(status=='DELIVERED'?'PEDIDO CONCLUÍDO':'ACOMPANHAMENTO AO VIVO',style:const TextStyle(color:Colors.white,fontSize:8,fontWeight:FontWeight.w900,letterSpacing:.7))])),const Spacer(),Text('#'+id.substring(0,id.length<8?id.length:8).toUpperCase(),style:const TextStyle(color:Colors.white60,fontSize:10,fontWeight:FontWeight.w800))]),const SizedBox(height:22),Text(_title(status),style:const TextStyle(color:Colors.white,fontSize:27,height:1.05,fontWeight:FontWeight.w900,letterSpacing:-.8)),const SizedBox(height:8),Text(_subtitle(status),style:const TextStyle(color:Color(0xFFD4ECE7),fontSize:11,height:1.45,fontWeight:FontWeight.w600)),const SizedBox(height:22),Row(children:[const Icon(Icons.payments_rounded,color:Color(0xFF8CFFE4),size:18),const SizedBox(width:8),Text(order['paymentStatus']=='PAID'?'Pagamento aprovado':'Pagamento ${order['paymentStatus']}',style:const TextStyle(color:Colors.white,fontSize:11,fontWeight:FontWeight.w800)),const Spacer(),Text(_money(order['total']),style:const TextStyle(color:Colors.white,fontSize:14,fontWeight:FontWeight.w900))]) ]));}
class _Journey extends StatelessWidget{const _Journey({required this.status,required this.step});final String status;final int step;@override Widget build(BuildContext context){final stages=[('Pagamento aprovado','Cobrança confirmada pelo Stripe.',Icons.verified_rounded),('Pedido recebido','A Porto Prime recebeu seu pedido.',Icons.receipt_long_rounded),('Em análise / confirmação','A distribuidora confere disponibilidade e libera os itens.',Icons.storefront_rounded),('Preparando','Seus produtos estão sendo separados.',Icons.inventory_2_rounded),('Aguardando entregador','Buscando um motoboy disponível.',Icons.search_rounded),('Entregador atribuído','Motoboy conectado ao pedido.',Icons.delivery_dining_rounded),('Saiu para entrega','Seu pedido está a caminho.',Icons.route_rounded),('Entregue','Pedido concluído.',Icons.home_filled)];return _Section(title:'Jornada do pedido',icon:Icons.timeline_rounded,child:Column(children:[for(var i=0;i<stages.length;i++)_Stage(stages[i].$3,stages[i].$1,stages[i].$2,i<=step,i==step,last:i==stages.length-1)]));}}
class _Stage extends StatelessWidget{const _Stage(this.icon,this.title,this.subtitle,this.done,this.current,{this.last=false});final IconData icon;final String title,subtitle;final bool done,current,last;@override Widget build(BuildContext context)=>IntrinsicHeight(child:Row(crossAxisAlignment:CrossAxisAlignment.stretch,children:[SizedBox(width:42,child:Column(children:[AnimatedContainer(duration:const Duration(milliseconds:300),width:38,height:38,decoration:BoxDecoration(color:done?AppColors.oceanDeep:AppColors.canvas,borderRadius:BorderRadius.circular(13),boxShadow:current?[BoxShadow(color:AppColors.oceanDeep.withValues(alpha:.18),blurRadius:14)]:null),child:Icon(done&& !current?Icons.check_rounded:icon,color:done?Colors.white:AppColors.muted,size:19)),if(!last)Expanded(child:Container(width:2,margin:const EdgeInsets.symmetric(vertical:5),color:iColor(done))) ])),const SizedBox(width:11),Expanded(child:Padding(padding:EdgeInsets.only(top:3,bottom:last?0:20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(fontSize:12.5,fontWeight:FontWeight.w900,color:done?AppColors.ink:AppColors.muted)),const SizedBox(height:3),Text(subtitle,style:const TextStyle(fontSize:9.5,height:1.4,color:AppColors.muted,fontWeight:FontWeight.w600))])))]));Color iColor(bool done)=>done?AppColors.oceanDeep:const Color(0xFFE5EAE7);}
class _Courier extends StatelessWidget{const _Courier({required this.courier});final dynamic courier;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(24)),child:Row(children:[Container(width:52,height:52,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(17)),child:const Icon(Icons.delivery_dining_rounded,color:AppColors.oceanDeep,size:28)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('SEU MOTOBOY',style:TextStyle(fontSize:8,color:AppColors.muted,fontWeight:FontWeight.w900)),Text(courier['user']?['name']??'Motoboy Porto Prime',style:const TextStyle(fontSize:15,fontWeight:FontWeight.w900)),if(courier['user']?['phone']!=null)Text(courier['user']['phone'].toString(),style:const TextStyle(fontSize:10,color:AppColors.muted))]))]));}
class _Section extends StatelessWidget{const _Section({required this.title,required this.icon,required this.child});final String title;final IconData icon;final Widget child;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(19),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(26),border:Border.all(color:const Color(0xFFE5EAE7))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:36,height:36,decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(12)),child:Icon(icon,size:19,color:AppColors.oceanDeep)),const SizedBox(width:10),Text(title,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w900))]),const SizedBox(height:17),child]));}
Widget _value(String a,dynamic b,{bool strong=false})=>Padding(padding:const EdgeInsets.only(top:7),child:Row(children:[Expanded(child:Text(a,style:TextStyle(fontSize:strong?13:10,color:strong?AppColors.ink:AppColors.muted,fontWeight:strong?FontWeight.w900:FontWeight.w700))),Text(_money(b),style:TextStyle(fontSize:strong?15:10,fontWeight:FontWeight.w900))]));
Widget _info(String a,String b)=>Padding(padding:const EdgeInsets.only(bottom:10),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:100,child:Text(a,style:const TextStyle(fontSize:10,color:AppColors.muted,fontWeight:FontWeight.w700))),Expanded(child:Text(b,textAlign:TextAlign.right,style:const TextStyle(fontSize:10,fontWeight:FontWeight.w900)))]));
String _money(dynamic v){final n=double.tryParse(v.toString())??0;return 'R\$ ${n.toStringAsFixed(2).replaceAll('.',',')}';}
String _date(dynamic v){if(v==null)return '—';final d=DateTime.tryParse(v.toString())?.toLocal();if(d==null)return v.toString();String t(int n)=>n.toString().padLeft(2,'0');return '${t(d.day)}/${t(d.month)}/${d.year} • ${t(d.hour)}:${t(d.minute)}';}
int _step(String s)=>switch(s){'PENDING'=>1,'CONFIRMED'=>2,'PREPARING'=>3,'READY_FOR_PICKUP'=>4,'COURIER_ASSIGNED'=>5,'PICKED_UP'=>5,'OUT_FOR_DELIVERY'=>6,'DELIVERED'=>7,'CANCELED'=>1,_=>1};
String _title(String s)=>switch(s){'PENDING'=>'Pedido recebido.','CONFIRMED'=>'Pedido em confirmação.','PREPARING'=>'Estamos preparando.','READY_FOR_PICKUP'=>'Pronto para coleta.','COURIER_ASSIGNED'=>'Motoboy encontrado.','PICKED_UP'=>'Pedido coletado.','OUT_FOR_DELIVERY'=>'Está chegando!','DELIVERED'=>'Pedido entregue.','CANCELED'=>'Pedido cancelado.',_=>'Pedido recebido.'};
String _subtitle(String s)=>switch(s){'PENDING'=>'Recebemos o pedido e aguardamos a confirmação do pagamento.','CONFIRMED'=>'Pagamento aprovado. A distribuidora está conferindo e liberando os itens.','PREPARING'=>'Seus produtos estão sendo separados com cuidado.','READY_FOR_PICKUP'=>'Tudo pronto. Estamos conectando um motoboy disponível.','COURIER_ASSIGNED'=>'Um motoboy foi atribuído e seguirá para a coleta.','PICKED_UP'=>'Seu pedido já está com o motoboy.','OUT_FOR_DELIVERY'=>'O motoboy está levando seu pedido até você.','DELIVERED'=>'Tudo certo. O histórico completo continua disponível aqui.','CANCELED'=>'Este pedido não seguirá para entrega.',_=>'Acompanhe as próximas etapas por aqui.'};
