import 'package:flutter/material.dart';
import '../../../../core/state/app_state.dart';
import '../../../../core/theme/app_theme.dart';
class HomePage extends StatefulWidget{const HomePage({super.key});@override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{
 final search=TextEditingController();
 @override void initState(){super.initState();if(AppState.instance.products.isEmpty)AppState.instance.bootstrap();}
 @override Widget build(BuildContext context)=>ListenableBuilder(listenable:AppState.instance,builder:(context,_){final s=AppState.instance;final q=search.text.toLowerCase();final products=s.products.where((p)=>q.isEmpty||p.name.toLowerCase().contains(q)).toList();return SafeArea(bottom:false,child:RefreshIndicator(onRefresh:s.bootstrap,child:CustomScrollView(slivers:[
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,18,20,8),sliver:SliverToBoxAdapter(child:Row(children:[Container(width:50,height:50,decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF00A98F),Color(0xFF087A61)]),borderRadius:BorderRadius.circular(17)),alignment:Alignment.center,child:const Text('P',style:TextStyle(color:Colors.white,fontSize:26,fontWeight:FontWeight.w900))),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('PORTO PRIME',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),SizedBox(height:2),Row(children:[Icon(Icons.location_on_rounded,size:14,color:Color(0xFFF2A900)),SizedBox(width:4),Text('Porto Seguro • Bahia',style:TextStyle(color:AppColors.muted,fontSize:12,fontWeight:FontWeight.w600))])])),Container(width:44,height:44,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.notifications_none_rounded))]))),
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,14,20,0),sliver:SliverToBoxAdapter(child:TextField(controller:search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(hintText:'Busque cerveja, whisky, gelo...',prefixIcon:Icon(Icons.search_rounded),suffixIcon:Icon(Icons.tune_rounded,color:AppColors.primaryDark))))),
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,18,20,0),sliver:SliverToBoxAdapter(child:Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(borderRadius:BorderRadius.circular(30),gradient:const LinearGradient(colors:[Color(0xFF006B5A),Color(0xFF12A889)],begin:Alignment.topLeft,end:Alignment.bottomRight),boxShadow:[BoxShadow(color:Color(0x22006B5A),blurRadius:24,offset:Offset(0,12))]),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:Colors.white24,borderRadius:BorderRadius.circular(20)),child:const Text('VERÃO O ANO INTEIRO',style:TextStyle(color:Colors.white,fontSize:10,fontWeight:FontWeight.w900,letterSpacing:.7))),const SizedBox(height:15),const Text('Bahia gelada.\nDo seu jeito.',style:TextStyle(color:Colors.white,fontSize:30,height:1.02,fontWeight:FontWeight.w900)),const SizedBox(height:9),const Text('Bebidas geladas e entrega rápida em Porto Seguro.',style:TextStyle(color:Color(0xFFE7FFF9),fontSize:13,height:1.35))])),const SizedBox(width:10),Container(width:88,height:132,decoration:BoxDecoration(color:const Color(0xFFFFC94A),borderRadius:BorderRadius.circular(26)),child:const Icon(Icons.local_drink_rounded,size:56,color:Color(0xFF075A4E)))])))),
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,26,20,12),sliver:SliverToBoxAdapter(child:Row(children:[Expanded(child:Text('Categorias',style:Theme.of(context).textTheme.titleLarge)),Text(s.categories.isEmpty?'Carregando...':'Explorar',style:const TextStyle(color:AppColors.primaryDark,fontWeight:FontWeight.w800))]))),
 SliverToBoxAdapter(child:SizedBox(height:98,child:ListView.separated(padding:const EdgeInsets.symmetric(horizontal:20),scrollDirection:Axis.horizontal,itemCount:s.categories.length,separatorBuilder:(_,i)=>const SizedBox(width:10),itemBuilder:(_,i){final c=s.categories[i];return Container(width:92,padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.local_bar_rounded,color:AppColors.primaryDark,size:27),const SizedBox(height:7),Text(c.name,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w800))]));}))),
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,25,20,12),sliver:SliverToBoxAdapter(child:Row(children:[Expanded(child:Text('Mais pedidos',style:Theme.of(context).textTheme.titleLarge)),const Text('Entrega rápida',style:TextStyle(color:Color(0xFFF2A900),fontWeight:FontWeight.w800,fontSize:12))]))),
 if(s.loading)const SliverToBoxAdapter(child:Padding(padding:EdgeInsets.all(40),child:Center(child:CircularProgressIndicator())))
 else if(s.error!=null)SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.all(20),child:Text(s.error!,style:const TextStyle(color:Colors.red))))
 else SliverPadding(padding:const EdgeInsets.fromLTRB(20,0,20,120),sliver:SliverList.separated(itemCount:products.length,separatorBuilder:(_,i)=>const SizedBox(height:11),itemBuilder:(_,i){final p=products[i];return Container(padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24)),child:Row(children:[Container(width:76,height:76,decoration:BoxDecoration(color:const Color(0xFFFFF4D8),borderRadius:BorderRadius.circular(20)),child:const Icon(Icons.sports_bar_rounded,color:AppColors.primaryDark,size:35)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p.name,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:15)),const SizedBox(height:5),Text(p.stock>0?'Disponível agora':'Indisponível',style:TextStyle(color:p.stock>0?AppColors.primaryDark:Colors.red,fontSize:11,fontWeight:FontWeight.w700)),const SizedBox(height:8),Text('R\$ '+p.price.toStringAsFixed(2).replaceAll('.',','),style:const TextStyle(fontWeight:FontWeight.w900,fontSize:17))])),FilledButton(onPressed:p.stock>0?(){s.add(p);ScaffoldMessenger.of(context).showSnackBar(SnackBar(duration:const Duration(milliseconds:700),content:Text(p.name+' adicionado')));}:null,style:FilledButton.styleFrom(shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)),padding:const EdgeInsets.all(13)),child:const Icon(Icons.add_rounded))]));}))
 ])));});
}
