import 'package:flutter/material.dart';
import '../../../../core/navigation/app_nav.dart';
import '../../../../core/state/app_state.dart';
import '../../../../core/theme/app_theme.dart';

class HomePage extends StatelessWidget{const HomePage({super.key});@override Widget build(BuildContext context)=>AnimatedBuilder(animation:AppState.instance,builder:(_,__){final s=AppState.instance;return SafeArea(bottom:false,child:CustomScrollView(physics:const BouncingScrollPhysics(),slivers:[
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,14,20,0),sliver:SliverToBoxAdapter(child:_Header(logged:s.loggedIn))),
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,16,20,0),sliver:SliverToBoxAdapter(child:_Search())),
 if(s.activeOrder!=null)SliverPadding(padding:const EdgeInsets.fromLTRB(20,12,20,0),sliver:SliverToBoxAdapter(child:_Active(order:s.activeOrder!))),
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,14,20,0),sliver:SliverToBoxAdapter(child:_Hero())),
 const SliverPadding(padding:EdgeInsets.fromLTRB(20,23,20,11),sliver:SliverToBoxAdapter(child:_Section('Escolha seu clima'))),
 const SliverToBoxAdapter(child:_Moments()),
 const SliverPadding(padding:EdgeInsets.fromLTRB(20,22,20,11),sliver:SliverToBoxAdapter(child:_Section('Gelou, chegou'))),
 SliverToBoxAdapter(child:SizedBox(height:244,child:s.products.isEmpty?const Center(child:CircularProgressIndicator()):ListView.separated(padding:const EdgeInsets.symmetric(horizontal:20),scrollDirection:Axis.horizontal,itemCount:s.products.length>8?8:s.products.length,separatorBuilder:(_,__)=>const SizedBox(width:12),itemBuilder:(_,i)=>_Product(p:s.products[i])))),
 SliverPadding(padding:const EdgeInsets.fromLTRB(20,22,20,125),sliver:SliverToBoxAdapter(child:_Promise())),
 ]));});}

class _Header extends StatelessWidget{const _Header({required this.logged});final bool logged;@override Widget build(BuildContext context)=>Row(children:[Container(width:47,height:47,decoration:BoxDecoration(gradient:const LinearGradient(colors:[AppColors.oceanDeep,AppColors.turquoise]),borderRadius:BorderRadius.circular(17)),alignment:Alignment.center,child:const Text('P',style:TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.w900))),const SizedBox(width:11),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('PORTO PRIME',style:TextStyle(fontSize:16,fontWeight:FontWeight.w900,letterSpacing:-.4)),SizedBox(height:2),Row(children:[Icon(Icons.near_me_rounded,size:12,color:AppColors.coral),SizedBox(width:4),Text('Porto Seguro • BA',style:TextStyle(fontSize:11,color:AppColors.muted,fontWeight:FontWeight.w700))])])),InkWell(onTap:()=>AppNav.instance.go(3),borderRadius:BorderRadius.circular(15),child:Container(width:44,height:44,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(15),border:Border.all(color:const Color(0xFFE8ECE8))),child:Icon(logged?Icons.person_rounded:Icons.person_outline_rounded,color:AppColors.oceanDeep)))]);}

class _Search extends StatelessWidget{const _Search();@override Widget build(BuildContext context)=>InkWell(onTap:()=>AppNav.instance.go(1),borderRadius:BorderRadius.circular(18),child:Container(height:54,padding:const EdgeInsets.symmetric(horizontal:15),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:const Color(0xFFE8EBE6))),child:const Row(children:[Icon(Icons.search_rounded,size:22),SizedBox(width:10),Expanded(child:Text('O que vai gelado hoje?',style:TextStyle(fontSize:12,color:AppColors.muted,fontWeight:FontWeight.w600))),Icon(Icons.tune_rounded,size:19,color:AppColors.oceanDeep)])));}

class _Active extends StatelessWidget{const _Active({required this.order});final Map<String,dynamic> order;@override Widget build(BuildContext context)=>InkWell(onTap:()=>AppNav.instance.go(3),borderRadius:BorderRadius.circular(18),child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:AppColors.sand,borderRadius:BorderRadius.circular(18)),child:Row(children:[Container(width:39,height:39,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(13)),child:const Icon(Icons.delivery_dining_rounded,color:AppColors.oceanDeep)),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Pedido em andamento',style:TextStyle(fontSize:12,fontWeight:FontWeight.w900)),Text(_status(order['status'].toString()),style:const TextStyle(fontSize:9,color:AppColors.muted,fontWeight:FontWeight.w700))])),const Icon(Icons.arrow_forward_rounded,size:18)])));}

class _Hero extends StatelessWidget{const _Hero();@override Widget build(BuildContext context)=>InkWell(onTap:()=>AppNav.instance.go(1),borderRadius:BorderRadius.circular(31),child:Container(height:250,clipBehavior:Clip.antiAlias,decoration:BoxDecoration(borderRadius:BorderRadius.circular(31),gradient:const LinearGradient(colors:[Color(0xFF063E39),Color(0xFF008C7E)],begin:Alignment.topLeft,end:Alignment.bottomRight),boxShadow:[BoxShadow(color:AppColors.ocean.withValues(alpha:.18),blurRadius:28,offset:const Offset(0,13))]),child:Stack(children:[Positioned(right:-65,top:-78,child:Container(width:220,height:220,decoration:const BoxDecoration(shape:BoxShape.circle,color:AppColors.sun))),Positioned(right:13,bottom:-17,child:Transform.rotate(angle:-.10,child:const Icon(Icons.sports_bar_rounded,size:137,color:Colors.white))),Padding(padding:const EdgeInsets.all(22),child:SizedBox(width:225,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[Icon(Icons.bolt_rounded,size:13,color:Color(0xFF8CFFE4)),SizedBox(width:5),Text('ENTREGA RÁPIDA • PORTO SEGURO',style:TextStyle(color:Color(0xFFD9FFF6),fontSize:8,fontWeight:FontWeight.w900,letterSpacing:.7))]),const SizedBox(height:15),const Text('Seu momento\ncontinua.',style:TextStyle(color:Colors.white,fontSize:32,height:.98,fontWeight:FontWeight.w900,letterSpacing:-1.2)),const SizedBox(height:9),const Text('A bebida chega. Você não precisa sair.',style:TextStyle(color:Color(0xFFD5F4EE),fontSize:12,height:1.35,fontWeight:FontWeight.w600)),const Spacer(),Container(padding:const EdgeInsets.symmetric(horizontal:15,vertical:11),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(14)),child:const Row(mainAxisSize:MainAxisSize.min,children:[Text('Explorar agora',style:TextStyle(color:AppColors.oceanDeep,fontSize:12,fontWeight:FontWeight.w900)),SizedBox(width:7),Icon(Icons.arrow_forward_rounded,size:16,color:AppColors.oceanDeep)]))])))])));}

class _Section extends StatelessWidget{const _Section(this.title);final String title;@override Widget build(BuildContext context)=>Row(children:[Expanded(child:Text(title,style:Theme.of(context).textTheme.titleLarge)),InkWell(onTap:()=>AppNav.instance.go(1),child:const Padding(padding:EdgeInsets.all(5),child:Text('Ver tudo',style:TextStyle(color:AppColors.oceanDeep,fontSize:10,fontWeight:FontWeight.w900))))]);}

class _Moments extends StatelessWidget{const _Moments();@override Widget build(BuildContext context)=>SizedBox(height:105,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:20),children:[_m('Praia','Pé na areia',Icons.beach_access_rounded,AppColors.sand),const SizedBox(width:10),_m('Churrasco','Sem faltar nada',Icons.outdoor_grill_rounded,const Color(0xFFFFDED1)),const SizedBox(width:10),_m('Noite','Drinks & amigos',Icons.nightlife_rounded,AppColors.mint)]));Widget _m(String a,String b,IconData i,Color c)=>InkWell(onTap:()=>AppNav.instance.go(1),borderRadius:BorderRadius.circular(22),child:Container(width:170,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:c,borderRadius:BorderRadius.circular(22)),child:Row(children:[Container(width:43,height:43,decoration:BoxDecoration(color:Colors.white.withValues(alpha:.75),borderRadius:BorderRadius.circular(14)),child:Icon(i,size:23)),const SizedBox(width:10),Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:13,fontWeight:FontWeight.w900)),Text(b,style:const TextStyle(fontSize:9,color:AppColors.muted,fontWeight:FontWeight.w700))]))])));}

class _Product extends StatelessWidget{const _Product({required this.p});final dynamic p;@override Widget build(BuildContext context){final s=AppState.instance,id=p['id'].toString(),price=double.tryParse(p['price'].toString())??0;return Container(width:165,padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24),border:Border.all(color:const Color(0xFFE8ECE8))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Container(width:double.infinity,clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(19)),child:p['imageUrl']!=null?Image.network(p['imageUrl'],fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.local_drink_rounded,size:52)):const Icon(Icons.local_drink_rounded,size:52))),const SizedBox(height:9),Text(p['name']??'',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w900)),Text(p['category']?['name']??'Porto Prime',style:const TextStyle(fontSize:9,color:AppColors.muted)),const Spacer(),Row(children:[Expanded(child:Text('R\$ '+price.toStringAsFixed(2).replaceAll('.',','),style:const TextStyle(fontSize:15,fontWeight:FontWeight.w900))),InkWell(onTap:()=>s.addProduct(id),borderRadius:BorderRadius.circular(12),child:Container(width:36,height:36,decoration:BoxDecoration(color:AppColors.ink,borderRadius:BorderRadius.circular(12)),child:const Icon(Icons.add_rounded,color:Colors.white)))]) ]));}}

class _Promise extends StatelessWidget{const _Promise();@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:const Color(0xFF17231F),borderRadius:BorderRadius.circular(26)),child:const Row(children:[DecoratedBox(decoration:BoxDecoration(color:Color(0xFF263A34),borderRadius:BorderRadius.all(Radius.circular(17))),child:SizedBox(width:53,height:53,child:Icon(Icons.bolt_rounded,color:AppColors.sun,size:29))),SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Gelada. Rápida. Sem complicação.',style:TextStyle(color:Colors.white,fontSize:14,fontWeight:FontWeight.w900)),SizedBox(height:3),Text('Da escolha ao acompanhamento, tudo em poucos toques.',style:TextStyle(color:Colors.white60,fontSize:10,height:1.35,fontWeight:FontWeight.w600))]))]));}

String _status(String s)=>switch(s){'PENDING'=>'Pedido recebido','CONFIRMED'=>'Pagamento confirmado','PREPARING'=>'Separando seu pedido','READY_FOR_PICKUP'=>'Pronto para coleta','COURIER_ASSIGNED'=>'Motoboy a caminho da coleta','PICKED_UP'=>'Pedido coletado','OUT_FOR_DELIVERY'=>'A caminho de você','DELIVERED'=>'Entregue',_=>s};
