import { afterEach, describe, expect, it, vi } from 'vitest';
vi.mock('../prisma/prisma.service.js',()=>({PrismaService:class{}}));
vi.mock('../auth/auth.service.js',()=>({AuthService:class{}}));
vi.mock('../realtime/realtime.gateway.js',()=>({RealtimeGateway:class{}}));
import { DeliveryPricingService } from './delivery-pricing.service.js';
const address:any={id:'a',street:'Rua Teste',number:'10',neighborhood:'Centro',city:'Porto Seguro',state:'BA',postalCode:'45810000',locationConfirmed:true,latitude:-16.45,longitude:-39.065};
function fixture(role='ADMIN',overrides:any={}) {
 const config:any={baseFee:5.5,includedKm:3,pricePerAdditionalKm:2.5,minDeliveryFee:20,maxDeliveryFee:6,maxDistanceKm:25,distributorLatitude:-16.449,distributorLongitude:-39.064,pricingRevision:1,...overrides};
 const db:any={customerCreditEntry:{aggregate:vi.fn(async()=>({_sum:{amount:0}})),create:vi.fn()},courierDemandSignal:{findUnique:vi.fn(async()=>({mode:'MANUAL_OFF',bonusAmount:2.5}))},order:{count:vi.fn(async()=>0)},deliveryPricingConfig:{upsert:vi.fn(async()=>config),update:vi.fn(async({data}:any)=>{const{pricingRevision,...rest}=data;Object.assign(config,rest);config.pricingRevision++;return config})},address:{findFirst:vi.fn(async()=>address)}};
 const events:any={emitCatalogUpdated:vi.fn()};const service=new DeliveryPricingService(db,{authenticate:async()=>({id:'customer',role})}as any,events);
 return{service,db,config,events};
}
function route(meters:number) {return vi.spyOn(globalThis,'fetch').mockResolvedValue({ok:true,json:async()=>({code:'Ok',routes:[{distance:meters,duration:600}]})}as Response)}
afterEach(()=>vi.restoreAllMocks());
describe('Tarifa proporcional pela rota viária',()=>{
 it.each([[0,5.5],[2999,5.5],[3000,5.5],[3001,5.5],[3250,6.13],[4000,8],[5000,10.5],[8000,18]])('cobra corretamente para %s metros',async(meters,expected)=>{route(meters);const f=fixture();const q=await f.service.quoteForAddress(address);expect(q.deliveryFee).toBe(expected);expect(q.courierSharePercent).toBe(100);expect(q.pricingMode).toBe('ROAD_ROUTE')});
 it('aplica os novos preços a uma rota em cache sem consultar novamente',async()=>{const fetch=route(5000);const f=fixture();await f.service.quoteForAddress(address);await f.service.updateAdminConfig({baseFee:6,includedKm:4,pricePerAdditionalKm:3});expect((await f.service.quoteForAddress(address)).deliveryFee).toBe(9);expect(fetch).toHaveBeenCalledTimes(1);expect(f.events.emitCatalogUpdated).toHaveBeenCalledWith('delivery.pricing.updated');expect(f.config.platformCommissionPercent).toBe(0)});
 it('deduplica consultas simultâneas de uma mesma rota',async()=>{const fetch=route(5000);const f=fixture();await Promise.all([f.service.quoteForAddress(address),f.service.quoteForAddress(address)]);expect(fetch).toHaveBeenCalledTimes(1)});
 it('não cobra taxa fictícia sem configurar a base',async()=>{const fetch=route(5000);const f=fixture('ADMIN',{distributorLatitude:null});await expect(f.service.quoteForAddress(address)).rejects.toThrow('ponto de retirada');expect(fetch).not.toHaveBeenCalled()});
 it('calcula endereços sem pedir confirmação em mapa',async()=>{route(5000);const f=fixture();(f.service as any).streets=[{street:'Rua Teste',number:'10',city:'Porto Seguro',latitude:-16.45,longitude:-39.065}];const q=await f.service.quoteForAddress({...address,locationConfirmed:false,latitude:null,longitude:null});expect(q.deliveryFee).toBe(10.5);expect(q.locationAccuracy).toBe('ADDRESS_NUMBER')});
 it('identifica estimativa de rua quando o número não está mapeado',async()=>{route(5000);const f=fixture();(f.service as any).streets=[{street:'Rua Teste',number:'',city:'Porto Seguro',latitude:-16.45,longitude:-39.065}];expect((await f.service.quoteForAddress({...address,locationConfirmed:false})).locationAccuracy).toBe('STREET_ESTIMATE')});
 it('não usa ruas apenas parecidas nem calcula distância fictícia',async()=>{const fetch=route(5000);const f=fixture();(f.service as any).streets=[{street:'Rua Teste Dois',number:'10',city:'Porto Seguro',latitude:-16.45,longitude:-39.065}];await expect(f.service.quoteForAddress({...address,locationConfirmed:false})).rejects.toThrow('nome completo');expect(fetch).not.toHaveBeenCalled()});
 it('rejeita ruas homônimas distantes sem bairro identificável',async()=>{const fetch=route(5000);const f=fixture();(f.service as any).streets=[{street:'Rua Teste',number:'',city:'Porto Seguro',latitude:-16.35,longitude:-39.065},{street:'Rua Teste',number:'',city:'Porto Seguro',latitude:-16.55,longitude:-39.065}];await expect(f.service.quoteForAddress({...address,locationConfirmed:false})).rejects.toThrow('bairro correto');expect(fetch).not.toHaveBeenCalled()});
 it('usa o bairro para desambiguar a rua',async()=>{route(5000);const f=fixture();(f.service as any).streets=[{street:'Rua Teste',number:'',city:'Porto Seguro',neighborhood:'Centro',latitude:-16.45,longitude:-39.065},{street:'Rua Teste',number:'',city:'Porto Seguro',neighborhood:'Outro',latitude:-16.55,longitude:-39.065}];expect((await f.service.quoteForAddress({...address,locationConfirmed:false})).deliveryFee).toBe(10.5)});
 it('preview ignora coordenadas enviadas e exige sessão de cliente',async()=>{const fetch=route(5000);const f=fixture('CUSTOMER');(f.service as any).streets=[{street:'Rua Teste',number:'10',city:'Porto Seguro',latitude:-16.46,longitude:-39.07}];const q=await f.service.preview(address);expect(q.locationAccuracy).toBe('ADDRESS_NUMBER');expect(String(fetch.mock.calls[0][0])).toContain('-39.07,-16.46');await expect(fixture('COURIER').service.preview(address)).rejects.toThrow('cliente')});

 it('recusa resposta inválida ou negativa do roteador',async()=>{route(-1);await expect(fixture().service.quoteForAddress(address)).rejects.toThrow('rota viária')});
 it('mantém o limite da área atendida e falha sem rota',async()=>{route(26000);await expect(fixture().service.quoteForAddress(address)).rejects.toThrow('fora da área')});
 it.each([null,'',-1,0,Infinity,NaN,2.555,true,[]])('recusa taxa inicial inválida %s',async value=>{const f=fixture();await expect(f.service.updateAdminConfig({baseFee:value})).rejects.toThrow();expect(f.db.deliveryPricingConfig.update).not.toHaveBeenCalled();expect(f.events.emitCatalogUpdated).not.toHaveBeenCalled()});
 it('não expõe endereço de outro cliente',async()=>{const f=fixture('CUSTOMER');f.db.address.findFirst.mockResolvedValue(null);await expect(f.service.customerQuote('another')).rejects.toThrow('não encontrado');expect(f.db.address.findFirst).toHaveBeenCalledWith({where:{id:'another',userId:'customer'}})});
 it('impede alteração de preço por cliente',async()=>{const f=fixture('CUSTOMER');await expect(f.service.updateAdminConfig({baseFee:1})).rejects.toThrow('administrador');expect(f.db.deliveryPricingConfig.update).not.toHaveBeenCalled()});
 it('preserva o despacho e ignora comissões enviadas',async()=>{const f=fixture();await f.service.updateAdminConfig({offerTimeoutSeconds:10,heartbeatTimeoutSeconds:600,platformCommissionPercent:20,maxDeliveryFee:1});expect(f.db.deliveryPricingConfig.update.mock.calls[0][0].data).toEqual({platformCommissionPercent:0,pricingRevision:{increment:1}})});
 it('não publica eventos quando a persistência falha',async()=>{const f=fixture();f.db.deliveryPricingConfig.update.mockRejectedValue(new Error('db'));await expect(f.service.updateAdminConfig({baseFee:6})).rejects.toThrow();expect(f.events.emitCatalogUpdated).not.toHaveBeenCalled()});
 it('usa somente o roteador local e não faz geocodificação pública',async()=>{const fetch=route(5000);await fixture().service.quoteForAddress(address);expect(String(fetch.mock.calls[0][0])).toContain('127.0.0.1:5000/route/v1/driving');expect(String(fetch.mock.calls[0][0])).toContain('radiuses=100%3B100')});
 it('valida o par de coordenadas da distribuidora',async()=>{const f=fixture();for(const body of [{distributorLatitude:-16},{distributorLatitude:91,distributorLongitude:0},{distributorLatitude:true,distributorLongitude:0}])await expect(f.service.updateAdminConfig(body)).rejects.toThrow('mapa');expect(f.db.deliveryPricingConfig.update).not.toHaveBeenCalled()});
 it('busca ruas nos dados locais sem confirmação em mapa',async()=>{const f=fixture('CUSTOMER');(f.service as any).streets=[{street:'Avenida dos Navegantes',number:'',city:'Porto Seguro',latitude:-16.45,longitude:-39.06},{street:'Avenida dos Navegantes',number:'10',city:'Porto Seguro',latitude:-16.46,longitude:-39.07},{street:'Avenida dos Navegantes',number:'11',city:'Outra Cidade',latitude:0,longitude:0}];const r=await f.service.locate({street:'Av dos Navegantes',number:'10',city:'Porto Seguro'});expect(r.requiresConfirmation).toBe(false);expect(r.results).toHaveLength(2);expect(r.results![0].number).toBe('10')});
 it('restringe busca de ruas a cliente ou administrador',async()=>{await expect(fixture('COURIER').service.locate({street:'Rua Teste'})).rejects.toThrow('permitido')});

});

describe('Busca de ruas e estabelecimentos selecionáveis',()=>{
 const hotel={id:'hotel',name:'Hotel Porto Azul',kind:'HOTEL',street:'Avenida Beira Mar',number:'20',neighborhood:'Taperapuan',city:'Porto Seguro',latitude:-16.4,longitude:-39.04};
 const street={id:'street',name:'Avenida Beira Mar',kind:'STREET',street:'Avenida Beira Mar',number:'',neighborhood:'Taperapuan',city:'Porto Seguro',latitude:-16.4,longitude:-39.04};
 function indexed(role='CUSTOMER'){const f=fixture(role);(f.service as any).places=[hotel,street,{...hotel,id:'other',city:'Outra Cidade'}];(f.service as any).placesLoadedAt=Date.now();(f.service as any).streets=[];return f;}
 it('sugere hotel por nome parcial sem misturar outra cidade',async()=>{const r=await indexed().service.searchPlaces('porto azul');expect(r.results).toHaveLength(1);expect(r.results[0].id).toBe('hotel')});
 it('sugere ruas durante a digitação e encontra palavras fora de ordem',async()=>{const r=await indexed().service.searchPlaces('mar beira');expect(r.results.map(p=>p.id)).toContain('street')});
 it('usa o hotel escolhido no cálculo mesmo quando não há rua no índice',async()=>{const fetch=route(5000);const q=await indexed().service.preview({...address,street:'Avenida Beira Mar',number:'',neighborhood:'',locationRef:'hotel'});expect(q.locationAccuracy).toBe('SELECTED_PLACE');expect(q.deliveryFee).toBe(10.5);expect(String(fetch.mock.calls[0][0])).toContain('-39.04,-16.4')});
 it('identifica a estimativa de rua selecionada sem inventar número',async()=>{route(3000);const q=await indexed().service.preview({...address,street:'Avenida Beira Mar',locationRef:'street'});expect(q.locationAccuracy).toBe('STREET_ESTIMATE');expect(q.deliveryFee).toBe(5.5)});
 it('recusa referência inexistente, local de outra cidade e rua alterada',async()=>{const f=indexed();for(const data of [{...address,locationRef:'invalid'},{...address,locationRef:'other'},{...address,locationRef:'street',street:'Rua Diferente'}])await expect(f.service.preview(data)).rejects.toThrow(/Selecione|selecione/);});
 it('exige sessão e limita consultas vazias ou enormes',async()=>{await expect(indexed('COURIER').service.searchPlaces('hotel')).rejects.toThrow('permitido');expect((await indexed().service.searchPlaces('ab')).results).toHaveLength(0);await expect(indexed().service.searchPlaces('x'.repeat(151))).rejects.toThrow('150')});
});

describe('Adicional de alta demanda na tarifa do cliente',()=>{
 it('soma adicional uma única vez à rota e remove da próxima cotação quando desligado',async()=>{route(3000);const f=fixture();f.db.courierDemandSignal.findUnique.mockResolvedValue({mode:'MANUAL_ON',bonusAmount:2.5});const q=await f.service.quoteForAddress(address);expect(q).toMatchObject({baseDeliveryFee:5.5,demandSurcharge:2.5,deliveryFee:8});f.db.courierDemandSignal.findUnique.mockResolvedValue({mode:'MANUAL_OFF',bonusAmount:2.5});expect((await f.service.quoteForAddress(address)).deliveryFee).toBe(5.5)});
 it('aplica adicional automático com dez pedidos pagos e conserva cobrança proporcional acima de 3 km',async()=>{route(5000);const f=fixture();f.db.courierDemandSignal.findUnique.mockResolvedValue({mode:'AUTO',bonusAmount:3});f.db.order.count.mockResolvedValue(10);expect(await f.service.quoteForAddress(address)).toMatchObject({baseDeliveryFee:10.5,demandSurcharge:3,deliveryFee:13.5});f.db.order.count.mockResolvedValue(9);expect((await f.service.quoteForAddress(address)).deliveryFee).toBe(10.5)});
});
