import 'dart:async';
import 'package:flutter/material.dart';
import '../../../../core/state/app_state.dart';
import '../../../../core/theme/app_theme.dart';

class CourierApplicationPage extends StatefulWidget {
  const CourierApplicationPage({super.key,this.initialCpf});
  final String? initialCpf;
  @override State<CourierApplicationPage> createState()=>_CourierApplicationPageState();
}
class _CourierApplicationPageState extends State<CourierApplicationPage>{
  final cpf=TextEditingController(); Map<String,dynamic>? data; String? error; bool busy=false; Timer? timer;
  @override void initState(){super.initState();cpf.text=widget.initialCpf??'';if(cpf.text.isNotEmpty){WidgetsBinding.instance.addPostFrameCallback((_)=>lookup());}}
  @override void dispose(){timer?.cancel();cpf.dispose();super.dispose();}
  Future<void> lookup({bool silent=false})async{if(cpf.text.replaceAll(RegExp(r'\\D'),'').length!=11){if(!silent)setState(()=>error='Informe um CPF completo.');return;}if(!silent)setState((){busy=true;error=null;});try{final x=await AppState.instance.courierApplication(cpf.text);if(!mounted)return;setState((){data=x;busy=false;error=null;});timer??=Timer.periodic(const Duration(seconds:5),(_)=>lookup(silent:true));}catch(e){if(mounted&&!silent)setState((){busy=false;error=e.toString().replaceFirst('Exception: ','');});}}
  String label(String s)=>{'PENDING':'Em análise','NEEDS_INFO':'Ação necessária','APPROVED':'Aprovado','REJECTED':'Não aprovado','SUSPENDED':'Suspenso'}[s]??s;
  Color tone(String s)=>s=='APPROVED'?AppColors.success:s=='NEEDS_INFO'?AppColors.coral:AppColors.oceanDeep;
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:AppColors.canvas,appBar:AppBar(backgroundColor:AppColors.canvas,title:const Text('Minha candidatura',style:TextStyle(fontWeight:FontWeight.w900))),body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,12,20,30),children:[
    if(data==null)...[
      Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(28),border:Border.all(color:AppColors.stroke)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
        Container(width:54,height:54,decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(18)),child:const Icon(Icons.manage_search_rounded,color:AppColors.oceanDeep,size:28)),const SizedBox(height:18),
        const Text('Já se candidatou?',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900,letterSpacing:-.7)),const SizedBox(height:7),const Text('Consulte o andamento da sua análise, veja solicitações da equipe e envie correções sem precisar criar outro cadastro.',style:TextStyle(fontSize:11.5,height:1.5,color:AppColors.muted,fontWeight:FontWeight.w600)),const SizedBox(height:20),
        TextField(controller:cpf,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'CPF usado no cadastro',hintText:'000.000.000-00',prefixIcon:const Icon(Icons.badge_outlined),filled:true,fillColor:AppColors.canvas,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide.none))),
        if(error!=null)Padding(padding:const EdgeInsets.only(top:10),child:Text(error!,style:const TextStyle(color:AppColors.coral,fontSize:11,fontWeight:FontWeight.w700))),const SizedBox(height:14),SizedBox(width:double.infinity,height:54,child:FilledButton.icon(onPressed:busy?null:lookup,icon:busy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Icon(Icons.search_rounded),label:const Text('Consultar candidatura',style:TextStyle(fontWeight:FontWeight.w900))))
      ])),
    ]else ...[
      _statusHero(),const SizedBox(height:14),_timeline(),const SizedBox(height:14),..._requirements(),const SizedBox(height:8),OutlinedButton.icon(onPressed:(){timer?.cancel();timer=null;setState(()=>data=null);},icon:const Icon(Icons.manage_search_rounded),label:const Text('Consultar outro CPF')),
    ]
  ])));
  Widget _statusHero(){final s=(data?['status']??'PENDING').toString();final approved=s=='APPROVED';return Container(padding:const EdgeInsets.all(21),decoration:BoxDecoration(gradient:LinearGradient(colors:approved?[AppColors.mint,const Color(0xFFF4FBF8)]:[Colors.white,AppColors.canvas]),borderRadius:BorderRadius.circular(28),border:Border.all(color:approved?AppColors.mintStrong:AppColors.stroke)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:50,height:50,decoration:BoxDecoration(color:tone(s).withValues(alpha:.12),borderRadius:BorderRadius.circular(17)),child:Icon(approved?Icons.verified_rounded:s=='NEEDS_INFO'?Icons.assignment_late_rounded:Icons.hourglass_top_rounded,color:tone(s))),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(data?['name']??'',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),Text(label(s),style:TextStyle(color:tone(s),fontSize:12,fontWeight:FontWeight.w900))]))]),const SizedBox(height:15),Text(approved?'Seu cadastro foi aprovado. Você já pode entrar na sua conta e começar a receber oportunidades de entrega.':s=='NEEDS_INFO'?'Precisamos de uma informação sua. Resolva as solicitações abaixo para sua análise continuar.':'Sua candidatura está com a equipe Porto Prime. Esta tela atualiza automaticamente a cada 5 segundos.',style:const TextStyle(fontSize:11,height:1.5,color:AppColors.muted,fontWeight:FontWeight.w600)),if(approved)...[const SizedBox(height:15),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>Navigator.pop(context),child:const Text('Entrar como motoboy',style:TextStyle(fontWeight:FontWeight.w900))))]]));}
  Widget _timeline(){final s=(data?['status']??'PENDING').toString();final idx=s=='APPROVED'?3:s=='NEEDS_INFO'?1:0;final names=['Cadastro recebido','Análise Porto Prime','Validação final','Aprovado'];return Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24),border:Border.all(color:AppColors.stroke)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('ANDAMENTO',style:TextStyle(fontSize:9,fontWeight:FontWeight.w900,letterSpacing:1.3,color:AppColors.muted)),const SizedBox(height:14),...List.generate(names.length,(i)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Row(children:[Icon(i<=idx?Icons.check_circle_rounded:Icons.radio_button_unchecked_rounded,color:i<=idx?AppColors.oceanDeep:AppColors.stroke,size:20),const SizedBox(width:10),Text(names[i],style:TextStyle(fontSize:11.5,fontWeight:i<=idx?FontWeight.w900:FontWeight.w600,color:i<=idx?AppColors.ink:AppColors.muted))])))]));}
  List<Widget> _requirements(){final rs=List<Map<String,dynamic>>.from((data?['requirements'] as List? ?? []).map((e)=>Map<String,dynamic>.from(e)));if(rs.isEmpty)return [Container(padding:const EdgeInsets.all(17),decoration:BoxDecoration(color:AppColors.mint,borderRadius:BorderRadius.circular(20)),child:const Row(children:[Icon(Icons.task_alt_rounded,color:AppColors.oceanDeep),SizedBox(width:11),Expanded(child:Text('Nenhuma pendência solicitada no momento.',style:TextStyle(fontSize:11,fontWeight:FontWeight.w800)))]))];return [const Padding(padding:EdgeInsets.only(bottom:9),child:Text('Solicitações da análise',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900))),...rs.map(_requirement)];}
  Widget _requirement(Map<String,dynamic> r){final status=(r['status']??'OPEN').toString(),open=status=='OPEN';return Container(margin:const EdgeInsets.only(bottom:11),padding:const EdgeInsets.all(17),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),border:Border.all(color:open?AppColors.coral.withValues(alpha:.45):AppColors.stroke)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(open?Icons.priority_high_rounded:status=='SUBMITTED'?Icons.schedule_send_rounded:Icons.check_circle_rounded,color:open?AppColors.coral:AppColors.oceanDeep),const SizedBox(width:9),Expanded(child:Text(r['title']??'Pendência',style:const TextStyle(fontSize:14,fontWeight:FontWeight.w900))),Text(status=='OPEN'?'AÇÃO NECESSÁRIA':status=='SUBMITTED'?'ENVIADO':'CONCLUÍDO',style:TextStyle(fontSize:8,fontWeight:FontWeight.w900,color:open?AppColors.coral:AppColors.oceanDeep))]),const SizedBox(height:8),Text(r['message']??'',style:const TextStyle(fontSize:11,height:1.45,color:AppColors.muted,fontWeight:FontWeight.w600)),if(r['response']!=null)...[const SizedBox(height:9),Container(width:double.infinity,padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:AppColors.canvas,borderRadius:BorderRadius.circular(13)),child:Text('Sua resposta: ${r['response']}',style:const TextStyle(fontSize:10.5,fontWeight:FontWeight.w700)))],if(open)...[const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>_respond(r),icon:const Icon(Icons.upload_file_rounded,size:18),label:const Text('Enviar o que foi solicitado',style:TextStyle(fontWeight:FontWeight.w900))))]]));}
  Future<void> _respond(Map<String,dynamic> r)async{final ctl=TextEditingController();await showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:Colors.transparent,builder:(ctx)=>Padding(padding:EdgeInsets.only(bottom:MediaQuery.viewInsetsOf(ctx).bottom),child:Container(padding:const EdgeInsets.all(20),decoration:const BoxDecoration(color:Colors.white,borderRadius:BorderRadius.vertical(top:Radius.circular(30))),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Responder solicitação',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text(r['title']??'',style:const TextStyle(color:AppColors.muted,fontWeight:FontWeight.w700)),const SizedBox(height:14),TextField(controller:ctl,maxLines:4,decoration:InputDecoration(hintText:'Informe os dados, número do documento ou esclarecimento solicitado...',filled:true,fillColor:AppColors.canvas,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide.none))),const SizedBox(height:12),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:()async{if(ctl.text.trim().length<3)return;try{await AppState.instance.submitCourierRequirement(r['id'],cpf.text,ctl.text);if(ctx.mounted)Navigator.pop(ctx);await lookup(silent:true);}catch(e){if(ctx.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}},child:const Text('Enviar para análise',style:TextStyle(fontWeight:FontWeight.w900))))]))));ctl.dispose();}
}
