import 'package:flutter/material.dart';
import '../../../../core/theme/app_theme.dart';
import '../../../../core/state/app_state.dart';

class ProfilePage extends StatelessWidget{const ProfilePage({super.key});@override Widget build(BuildContext context)=>AnimatedBuilder(animation:AppState.instance,builder:(_,__)=>AppState.instance.loggedIn?const _Account():const _Guest());}

class _Guest extends StatelessWidget{const _Guest();@override Widget build(BuildContext context)=>SafeArea(bottom:false,child:ListView(padding:const EdgeInsets.fromLTRB(20,22,20,120),children:[
 Text('Seu espaço',style:Theme.of(context).textTheme.headlineLarge),const SizedBox(height:6),const Text('Entre ou crie sua conta Porto Prime.',style:TextStyle(color:AppColors.muted,fontWeight:FontWeight.w600)),const SizedBox(height:22),
 Container(padding:const EdgeInsets.all(21),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF15302B),Color(0xFF08786D)]),borderRadius:BorderRadius.circular(28)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
  const Icon(Icons.person_rounded,color:Colors.white,size:32),const SizedBox(height:14),const Text('Já tem uma conta?',style:TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:5),const Text('Acesse pedidos, entregas e sua conta.',style:TextStyle(color:Colors.white70,fontSize:12)),
  const SizedBox(height:17),SizedBox(width:double.infinity,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:Colors.white,foregroundColor:AppColors.oceanDeep,padding:const EdgeInsets.all(15)),onPressed:()=>_auth(context),child:const Text('Entrar',style:TextStyle(fontWeight:FontWeight.w900)))),
 ])),const SizedBox(height:23),const Text('Quero criar uma conta',style:TextStyle(fontSize:16,fontWeight:FontWeight.w900)),const SizedBox(height:11),
 _Role('Cliente','Peça bebidas e acompanhe seus pedidos.',Icons.shopping_bag_rounded,AppColors.sand,()=>_register(context,'CUSTOMER')),
 _Role('Motoboy','Receba corridas após aprovação.',Icons.delivery_dining_rounded,AppColors.mint,()=>_register(context,'COURIER')),
 _Role('Parceiro','Hotéis e pousadas conectados à Porto Prime.',Icons.apartment_rounded,const Color(0xFFFFE1DB),()=>_register(context,'PARTNER')),
]));}

class _Role extends StatelessWidget{const _Role(this.a,this.b,this.i,this.c,this.tap);final String a,b;final IconData i;final Color c;final VoidCallback tap;@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:10),child:InkWell(onTap:tap,borderRadius:BorderRadius.circular(22),child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),border:Border.all(color:const Color(0xFFE8EBE6))),child:Row(children:[Container(width:52,height:52,decoration:BoxDecoration(color:c,borderRadius:BorderRadius.circular(17)),child:Icon(i,color:AppColors.ink)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w900)),const SizedBox(height:3),Text(b,style:const TextStyle(fontSize:10,color:AppColors.muted,fontWeight:FontWeight.w600))])),const Icon(Icons.arrow_forward_rounded,size:19)]))));}

Future<void> _auth(BuildContext context)async{final e=TextEditingController(),p=TextEditingController();await showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:Colors.transparent,builder:(ctx)=>_Sheet(title:'Entrar na Porto Prime',children:[
 _field(e,'E-mail',Icons.mail_outline_rounded,type:TextInputType.emailAddress),_field(p,'Senha',Icons.lock_outline_rounded,secret:true),_submit(ctx,'Entrar',()async{await AppState.instance.login(e.text,p.text);if(ctx.mounted)Navigator.pop(ctx);})
]));}

Future<void> _register(BuildContext context,String role)async{final n=TextEditingController(),e=TextEditingController(),ph=TextEditingController(),p=TextEditingController(),doc=TextEditingController(),biz=TextEditingController();final label=role=='CUSTOMER'?'Cliente':role=='COURIER'?'Motoboy':'Parceiro';await showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:Colors.transparent,builder:(ctx)=>_Sheet(title:'Cadastro de '+label,subtitle:role=='CUSTOMER'?'Sua conta fica ativa na hora.':'Seu cadastro será enviado para aprovação do administrador.',children:[
 _field(n,'Nome completo',Icons.person_outline_rounded),if(role=='PARTNER')_field(biz,'Nome do estabelecimento',Icons.storefront_rounded),_field(e,'E-mail',Icons.mail_outline_rounded,type:TextInputType.emailAddress),_field(ph,'Telefone',Icons.phone_outlined,type:TextInputType.phone),if(role!='CUSTOMER')_field(doc,role=='COURIER'?'CPF / documento':'CNPJ / documento',Icons.badge_outlined),_field(p,'Senha (mínimo 8 caracteres)',Icons.lock_outline_rounded,secret:true),
 _submit(ctx,'Criar conta',()async{await AppState.instance.register({'name':n.text,'email':e.text,'phone':ph.text,'password':p.text,'role':role,if(role!='CUSTOMER')'document':doc.text,if(role=='PARTNER')'businessName':biz.text});if(ctx.mounted)Navigator.pop(ctx);})
]));}

Widget _field(TextEditingController c,String label,IconData i,{bool secret=false,TextInputType? type})=>Padding(padding:const EdgeInsets.only(bottom:11),child:TextField(controller:c,obscureText:secret,keyboardType:type,style:const TextStyle(fontSize:16),decoration:InputDecoration(labelText:label,prefixIcon:Icon(i),filled:true,fillColor:AppColors.canvas,border:OutlineInputBorder(borderRadius:BorderRadius.circular(17),borderSide:BorderSide.none))));
Widget _submit(BuildContext ctx,String label,Future<void> Function() go)=>AnimatedBuilder(animation:AppState.instance,builder:(_,__)=>Column(children:[if(AppState.instance.error!=null)Padding(padding:const EdgeInsets.only(bottom:9),child:Text(AppState.instance.error!,style:const TextStyle(color:Colors.red,fontSize:11))),SizedBox(width:double.infinity,height:54,child:FilledButton(onPressed:AppState.instance.loading?null:()async{try{await go();}catch(_){}},style:FilledButton.styleFrom(backgroundColor:AppColors.oceanDeep),child:AppState.instance.loading?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):Text(label,style:const TextStyle(fontWeight:FontWeight.w900))))]));

class _Sheet extends StatelessWidget{const _Sheet({required this.title,this.subtitle,required this.children});final String title;final String? subtitle;final List<Widget> children;@override Widget build(BuildContext context)=>Container(padding:EdgeInsets.fromLTRB(20,20,20,20+MediaQuery.viewInsetsOf(context).bottom),decoration:const BoxDecoration(color:Colors.white,borderRadius:BorderRadius.vertical(top:Radius.circular(30))),child:SafeArea(top:false,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[Row(children:[Expanded(child:Text(title,style:const TextStyle(fontSize:23,fontWeight:FontWeight.w900))),IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.close_rounded))]),if(subtitle!=null)...[Text(subtitle!,style:const TextStyle(color:AppColors.muted,fontSize:11)),const SizedBox(height:15)]else const SizedBox(height:10),...children]))));}

class _Account extends StatelessWidget{const _Account();@override Widget build(BuildContext context){final s=AppState.instance,u=s.user!,pending=u['status']=='PENDING';return SafeArea(bottom:false,child:ListView(padding:const EdgeInsets.fromLTRB(20,22,20,120),children:[
 Text('Sua conta',style:Theme.of(context).textTheme.headlineLarge),const SizedBox(height:18),Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:AppColors.ink,borderRadius:BorderRadius.circular(28)),child:Row(children:[const CircleAvatar(radius:28,backgroundColor:AppColors.mint,child:Icon(Icons.person_rounded,color:AppColors.oceanDeep)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(u['name']??'',style:const TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.w900)),Text(u['email']??'',style:const TextStyle(color:Colors.white60,fontSize:11))]))])),
 if(pending)...[const SizedBox(height:14),Container(padding:const EdgeInsets.all(17),decoration:BoxDecoration(color:AppColors.sand,borderRadius:BorderRadius.circular(21)),child:const Row(children:[Icon(Icons.hourglass_top_rounded,color:AppColors.coral),SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Cadastro em análise',style:TextStyle(fontWeight:FontWeight.w900)),SizedBox(height:3),Text('Você poderá acessar a área operacional após aprovação do administrador.',style:TextStyle(fontSize:10,color:AppColors.muted))]))]))],
 if(s.isCustomer)...[const SizedBox(height:18),_line('Meus pedidos',Icons.receipt_long_rounded,()=>_orders(context)),_line('Endereços',Icons.location_on_rounded,()=>_addresses(context))],
 const SizedBox(height:18),OutlinedButton.icon(onPressed:()=>s.logout(),icon:const Icon(Icons.logout_rounded),label:const Text('Sair da conta')),
]));}}

Widget _line(String a,IconData i,VoidCallback tap)=>ListTile(onTap:tap,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18)),tileColor:Colors.white,leading:Icon(i,color:AppColors.oceanDeep),title:Text(a,style:const TextStyle(fontWeight:FontWeight.w800)),trailing:const Icon(Icons.chevron_right_rounded));

void _orders(BuildContext context){showModalBottomSheet(context:context,isScrollControlled:true,builder:(c)=>SafeArea(child:Padding(padding:const EdgeInsets.all(20),child:AppState.instance.orders.isEmpty?const Center(child:Text('Você ainda não tem pedidos.')):ListView(children:[const Text('Meus pedidos',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:15),...AppState.instance.orders.map((o)=>ListTile(title:Text('Pedido '+o['id'].toString().substring(0,8)),subtitle:Text(o['status'].toString()),trailing:Text('R\$ '+o['total'].toString())))]))));}
void _addresses(BuildContext context){showModalBottomSheet(context:context,isScrollControlled:true,builder:(c)=>SafeArea(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[const Text('Endereços',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:10),Expanded(child:ListView(children:AppState.instance.addresses.map((a)=>ListTile(leading:const Icon(Icons.location_on_outlined),title:Text((a['street']??'')+', '+(a['number']??'')),subtitle:Text(a['neighborhood']??''))).toList())),FilledButton(onPressed:()=>_newAddress(c),child:const Text('Adicionar endereço'))]))));}
void _newAddress(BuildContext context){final st=TextEditingController(),no=TextEditingController(),ne=TextEditingController(),cep=TextEditingController();showDialog(context:context,builder:(c)=>AlertDialog(title:const Text('Novo endereço'),content:SingleChildScrollView(child:Column(children:[_field(st,'Rua',Icons.route),_field(no,'Número',Icons.numbers),_field(ne,'Bairro',Icons.map_outlined),_field(cep,'CEP',Icons.local_post_office_outlined)])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancelar')),FilledButton(onPressed:()async{try{await AppState.instance.addAddress({'street':st.text,'number':no.text,'neighborhood':ne.text,'city':'Porto Seguro','state':'BA','postalCode':cep.text,'isDefault':true});if(c.mounted)Navigator.pop(c);}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(e.toString())));}},child:const Text('Salvar'))]));}
