import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { CourierStatus, UserRole, UserStatus } from '../generated/prisma/client.js';
import { AuthService } from '../auth/auth.service.js';
import { PrismaService } from '../prisma/prisma.service.js';
@Injectable()
export class AdminService {
 constructor(private readonly prisma:PrismaService,private readonly auth:AuthService){}
 private async requireAdmin(a?:string){const u=await this.auth.authenticate(a);if(u.role!==UserRole.ADMIN)throw new ForbiddenException('Acesso exclusivo do administrador');return u;}
 async pending(a?:string){await this.requireAdmin(a);return this.prisma.user.findMany({where:{status:UserStatus.PENDING,role:{in:[UserRole.COURIER,UserRole.PARTNER]}},select:{id:true,name:true,email:true,phone:true,role:true,status:true,courierProfile:true,partnerProfile:true,createdAt:true},orderBy:{createdAt:'asc'}});}
 async couriers(a?:string){await this.requireAdmin(a);return (this.prisma as any).courierProfile.findMany({include:{user:{select:{id:true,name:true,email:true,phone:true,status:true}},requirements:{orderBy:{requestedAt:'desc'}}},orderBy:{createdAt:'desc'}});}
 async approve(userId:string,a?:string){await this.requireAdmin(a);const user=await this.prisma.user.findUnique({where:{id:userId},include:{courierProfile:true,partnerProfile:true}});if(!user)throw new NotFoundException('Usuário não encontrado');return this.prisma.$transaction(async tx=>{if(user.role===UserRole.COURIER&&user.courierProfile){const open=await (tx as any).courierRequirement.count({where:{courierId:user.courierProfile.id,status:{not:'RESOLVED'}}});if(open)throw new BadRequestException('Resolva todas as pendências antes de aprovar');await tx.courierProfile.update({where:{id:user.courierProfile.id},data:{approvalStatus:CourierStatus.APPROVED}});}else if(user.role===UserRole.PARTNER&&user.partnerProfile){await tx.partnerProfile.update({where:{id:user.partnerProfile.id},data:{approved:true}});}else throw new ForbiddenException('Perfil não requer aprovação');return tx.user.update({where:{id:userId},data:{status:UserStatus.ACTIVE},select:{id:true,name:true,email:true,role:true,status:true}});});}
 async reject(userId:string,a?:string){await this.requireAdmin(a);const user=await this.prisma.user.findUnique({where:{id:userId},include:{courierProfile:true,partnerProfile:true}});if(!user)throw new NotFoundException('Usuário não encontrado');if(user.role===UserRole.COURIER&&user.courierProfile)await this.prisma.courierProfile.update({where:{id:user.courierProfile.id},data:{approvalStatus:CourierStatus.REJECTED,isOnline:false}});return this.prisma.user.update({where:{id:userId},data:{status:UserStatus.BLOCKED},select:{id:true,name:true,email:true,role:true,status:true}});}
 async createRequirement(courierId:string,body:{title:string;description:string},a?:string){await this.requireAdmin(a);if(!body.title?.trim()||!body.description?.trim())throw new BadRequestException('Título e descrição são obrigatórios');const p=await (this.prisma as any).courierProfile.findUnique({where:{id:courierId}});if(!p)throw new NotFoundException('Motoboy não encontrado');return (this.prisma as any).courierRequirement.create({data:{courierId,title:body.title.trim(),description:body.description.trim()}});}
 async resolveRequirement(id:string,a?:string){await this.requireAdmin(a);const r=await (this.prisma as any).courierRequirement.findUnique({where:{id}});if(!r)throw new NotFoundException('Pendência não encontrada');return (this.prisma as any).courierRequirement.update({where:{id},data:{status:'RESOLVED',resolvedAt:new Date()}});}
}