import { describe, it, expect, vi } from 'vitest';
vi.mock('../prisma/prisma.service.js',()=>({PrismaService:class{}}));
vi.mock('../auth/auth.service.js',()=>({AuthService:class{}}));
vi.mock('../dispatch/dispatch.service.js',()=>({DispatchService:class{}}));
vi.mock('../wallet/wallet.service.js',()=>({WalletService:class{}}));
vi.mock('../realtime/realtime.gateway.js',()=>({RealtimeGateway:class{}}));
vi.mock('../generated/prisma/client.js',()=>({UserRole:{ADMIN:'ADMIN',COURIER:'COURIER'},CourierStatus:{},OrderStatus:{},PaymentStatus:{},UserStatus:{}}));
import { AdminService } from './admin.service.js';
function fixture(role='ADMIN'){
 const profile:any={id:'c',userId:'u',pixKey:'old@example.test',pixKeyType:'EMAIL',document:'52998224725',onboardingData:{street:'Old',cpf:'52998224725',birthDate:'01/01/1990',reference:'Old reference',cpfSituation:'REGULAR'},isOnline:true};
 const tx:any={$queryRawUnsafe:vi.fn(async()=>[]),courierProfile:{findUnique:vi.fn(async()=>profile),update:vi.fn(async()=>({})),findFirst:vi.fn(async()=>null)},user:{update:vi.fn(async()=>({}))}};
 const prisma:any={...tx,$transaction:vi.fn(async(fn:any)=>fn(tx)),order:{count:async()=>3,findMany:vi.fn(async()=>[])},courierLedgerEntry:{aggregate:vi.fn(async({where}:any)=>({_sum:{amount:where.type?120:40}}))},withdrawal:{findMany:async()=>[{status:'PAID',amount:50},{status:'PROCESSING',amount:20},{status:'PENDING',amount:10},{status:'REJECTED',amount:5}]}};
 const auth:any={authenticate:async()=>({role}),verifyCourierIdentityForAdmin:vi.fn(async(cpf:string,birthDate:string)=>({cpf,name:'Nome Verificado',birthDate,situation:'REGULAR',regular:true}))};const realtime:any={emitToUser:vi.fn(),emitToRole:vi.fn(),emitOrderUpdated:vi.fn()};
 return {tx,prisma,realtime,auth,service:new AdminService(prisma,auth,{} as any,{} as any,realtime)};
}
describe('Admin courier profile and finance',()=>{
 it('rejects non-admin reads and edits',async()=>{const f=fixture('COURIER');await expect(f.service.courierFinance('c')).rejects.toThrow('administrador');await expect(f.service.editCourier('c',{name:'Name'})).rejects.toThrow('administrador');expect(f.prisma.$transaction).not.toHaveBeenCalled()});
 it('separates paid, pending and rejected withdrawals',async()=>{const f=fixture();expect(await f.service.courierFinance('c')).toMatchObject({earningsTotal:120,availableBalance:40,deliveries:3,paidWithdrawalCount:1,paidWithdrawalTotal:50,pendingWithdrawalTotal:30})});
 it('preserves CPF and availability while merging changes',async()=>{const f=fixture();await f.service.editCourier('c',{street:'New',name:'New Name',pixKey:'NEW@example.test',pixKeyType:'EMAIL'});const data=f.tx.courierProfile.update.mock.calls[0][0].data;expect(data.onboardingData).toMatchObject({cpf:'52998224725',street:'New',pixKey:'new@example.test'});expect(data).not.toHaveProperty('isOnline');expect(data).not.toHaveProperty('document');expect(f.realtime.emitToUser).toHaveBeenCalledWith('u','courier.profile.updated',{courierId:'c'})});
 it('rejects protected fields and invalid values',async()=>{for(const body of [{isOnline:false},{cpfSituation:'IRREGULAR'},{email:'invalid'},{vehicleYear:'1900'},{cnhCategory:'Z'}]){const f=fixture();await expect(f.service.editCourier('c',body)).rejects.toThrow();expect(f.prisma.$transaction).not.toHaveBeenCalled()}});
 it('does not emit updates when transaction fails',async()=>{const f=fixture();f.tx.user.update.mockRejectedValue({code:'P2002'});await expect(f.service.editCourier('c',{email:'new@example.test'})).rejects.toThrow('já está cadastrado');expect(f.realtime.emitToUser).not.toHaveBeenCalled()});
});

describe('Edição completa da ficha cadastral',()=>{
 it('salva a foto validada e atualiza também os clientes de entregas ativas',async()=>{const f=fixture();const photo='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==';f.prisma.order.findMany.mockResolvedValue([{id:'o',customerId:'customer',status:'OUT_FOR_DELIVERY'}]);await f.service.editCourier('c',{profilePhoto:photo});expect(f.tx.courierProfile.update.mock.calls[0][0].data.onboardingData.profilePhoto).toBe(photo);expect(f.realtime.emitOrderUpdated).toHaveBeenCalledWith({id:'o',customerId:'customer',status:'OUT_FOR_DELIVERY'})});

 it('altera CPF e nascimento somente após verificação, atualizando a identidade canônica',async()=>{const f=fixture();await f.service.editCourier('c',{cpf:'11144477735',birthDate:'1991-02-03',name:'Nome digitado'});expect(f.auth.verifyCourierIdentityForAdmin).toHaveBeenCalledWith('11144477735','03/02/1991');expect(f.tx.courierProfile.update.mock.calls[0][0].data).toMatchObject({document:'11144477735',onboardingData:{cpf:'11144477735',birthDate:'03/02/1991',cpfSituation:'REGULAR',name:'Nome Verificado'}});expect(f.tx.user.update.mock.calls[0][0].data.name).toBe('Nome Verificado')});
 it('bloqueia CPF já utilizado por outro perfil',async()=>{const f=fixture();f.tx.courierProfile.findFirst.mockResolvedValue({id:'other'});await expect(f.service.editCourier('c',{cpf:'11144477735'})).rejects.toThrow('já possui');expect(f.auth.verifyCourierIdentityForAdmin).not.toHaveBeenCalled();expect(f.tx.courierProfile.update).not.toHaveBeenCalled()});
 it('não persiste quando a consulta de identidade falha',async()=>{const f=fixture();f.auth.verifyCourierIdentityForAdmin.mockRejectedValue(new Error('CPF irregular'));await expect(f.service.editCourier('c',{cpf:'11144477735'})).rejects.toThrow('irregular');expect(f.tx.courierProfile.update).not.toHaveBeenCalled();expect(f.realtime.emitToUser).not.toHaveBeenCalled()});
 it('permite alterar informações adicionais existentes, sem sobrescrever outros dados',async()=>{const f=fixture();await f.service.editCourier('c',{hasMotorcycle:true,extraData:{reference:'New reference'}});expect(f.tx.courierProfile.update.mock.calls[0][0].data.onboardingData).toMatchObject({hasMotorcycle:true,reference:'New reference',cpf:'52998224725',street:'Old'})});
 it('recusa campos adicionais desconhecidos ou resultados de verificação',async()=>{for(const extraData of [{unknown:'injected'},{cpfSituation:'REGULAR'}]){const f=fixture();await expect(f.service.editCourier('c',{extraData})).rejects.toThrow('não permitido');expect(f.tx.courierProfile.update).not.toHaveBeenCalled();expect(f.realtime.emitToUser).not.toHaveBeenCalled()}});
 it('recusa foto inválida e booleano inválido antes da persistência',async()=>{for(const body of [{profilePhoto:'https://example.test/photo.jpg'},{hasMotorcycle:'true'}]){const f=fixture();await expect(f.service.editCourier('c',body)).rejects.toThrow();expect(f.prisma.$transaction).not.toHaveBeenCalled()}});
});
